<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 10 Analyzing Census microdata | Analyzing US Census Data</title>
<meta name="author" content="Kyle E. Walker">
<meta name="description" content="A major benefit of using the individual-level microdata returned by get_pums() is the ability to create detailed, granular estimates of ACS data. While the aggregate ACS data available with...">
<meta name="generator" content="bookdown 0.22.17 with bs4_book()">
<meta property="og:title" content="Chapter 10 Analyzing Census microdata | Analyzing US Census Data">
<meta property="og:type" content="book">
<meta property="og:url" content="https://walker-data.com/census-r/analyzing-census-microdata.html">
<meta property="og:image" content="https://walker-data.com/census-r/04-visualizing-census-data_files/figure-html/visualize-error-bars-1.png">
<meta property="og:description" content="A major benefit of using the individual-level microdata returned by get_pums() is the ability to create detailed, granular estimates of ACS data. While the aggregate ACS data available with...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 10 Analyzing Census microdata | Analyzing US Census Data">
<meta name="twitter:description" content="A major benefit of using the individual-level microdata returned by get_pums() is the ability to create detailed, granular estimates of ACS data. While the aggregate ACS data available with...">
<meta name="twitter:image" content="https://walker-data.com/census-r/04-visualizing-census-data_files/figure-html/visualize-error-bars-1.png">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.10.5/header-attrs.js"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.0/transition.js"></script><script src="libs/bs3compat-0.3.0/tabs.js"></script><script src="libs/bs3compat-0.3.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script><script src="libs/plotly-binding-4.9.3/plotly.js"></script><script src="libs/typedarray-0.1/typedarray.min.js"></script><link href="libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet">
<script src="libs/crosstalk-1.1.1/js/crosstalk.min.js"></script><link href="libs/plotly-htmlwidgets-css-1.57.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="libs/plotly-main-1.57.1/plotly-latest.min.js"></script><script src="libs/d3-bundle-5.16.0/d3-bundle.min.js"></script><script src="libs/d3-lasso-0.0.5/d3-lasso.min.js"></script><script src="libs/save-svg-as-png-1.4.17/save-svg-as-png.min.js"></script><link href="libs/ggiraphjs-0.4.1/ggiraphjs.min.css" rel="stylesheet">
<script src="libs/ggiraphjs-0.4.1/ggiraphjs.min.js"></script><script src="libs/girafe-binding-0.7.10/girafe.js"></script><!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=G-6KFYZ3W36Z"></script><script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-6KFYZ3W36Z');
    </script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS -->
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="Methods, Maps, and Models in R">Analyzing US Census Data</a>:
        <small class="text-muted">Methods, Maps, and Models in R</small>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Preface</a></li>
<li><a class="" href="the-united-states-census-and-the-r-programming-language.html"><span class="header-section-number">1</span> The United States Census and the R programming language</a></li>
<li><a class="" href="an-introduction-to-tidycensus.html"><span class="header-section-number">2</span> An introduction to tidycensus</a></li>
<li><a class="" href="wrangling-census-data-with-tidyverse-tools.html"><span class="header-section-number">3</span> Wrangling Census data with tidyverse tools</a></li>
<li><a class="" href="exploring-us-census-data-with-visualization.html"><span class="header-section-number">4</span> Exploring US Census data with visualization</a></li>
<li><a class="" href="census-geographic-data-and-applications-in-r.html"><span class="header-section-number">5</span> Census geographic data and applications in R</a></li>
<li><a class="" href="mapping-census-data-with-r.html"><span class="header-section-number">6</span> Mapping Census data with R</a></li>
<li><a class="" href="spatial-analysis-with-us-census-data.html"><span class="header-section-number">7</span> Spatial analysis with US Census data</a></li>
<li><a class="" href="modeling-us-census-data.html"><span class="header-section-number">8</span> Modeling US Census data</a></li>
<li><a class="" href="introduction-to-census-microdata.html"><span class="header-section-number">9</span> Introduction to Census microdata</a></li>
<li><a class="active" href="analyzing-census-microdata.html"><span class="header-section-number">10</span> Analyzing Census microdata</a></li>
<li><a class="" href="other-census-and-government-data-resources.html"><span class="header-section-number">11</span> Other Census and government data resources</a></li>
<li><a class="" href="working-with-census-data-outside-the-united-states.html"><span class="header-section-number">12</span> Working with Census data outside the United States</a></li>
<li><a class="" href="conclusion.html">Conclusion</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="analyzing-census-microdata" class="section level1" number="10">
<h1>
<span class="header-section-number">10</span> Analyzing Census microdata<a class="anchor" aria-label="anchor" href="#analyzing-census-microdata"><i class="fas fa-link"></i></a>
</h1>
<p>A major benefit of using the individual-level microdata returned by <code><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums()</a></code> is the ability to create detailed, granular estimates of ACS data. While the aggregate ACS data available with <code><a href="https://walker-data.com/tidycensus/reference/get_acs.html">get_acs()</a></code> includes tens of thousands of indicators to choose from, researchers and analysts still may be interested in cross-tabulations not available in the aggregate files. Additionally, microdata helps researchers design statistical models to assess demographic relationships at the individual level in a way not possible with aggregate data.</p>
<p>Analysts must pay careful attention to the structure of the PUMS datasets in order to produce accurate estimates and handle errors appropriately. PUMS datasets are <em>weighted</em> samples, in which each person or household is not considered unique or individual, but rather representative of multiple other persons or households. In turn, analyses and tabulations using PUMS data must use appropriate tools for handling weighting variables to accurately produce estimates. Fortunately, tidyverse tools like <strong>dplyr</strong>, covered elsewhere in this book, are excellent for producing these tabulations and handling survey weights</p>
<p>As covered in Chapter 3, data from the American Community Survey are based on a sample and in turn characterized by error. This means that ACS data acquired with <code><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums()</a></code> are similarly characterized by error, which can be substantial when cross-tabulations are highly specific. Fortunately, the US Census Bureau provides <em>replicate weights</em> to help analysts generate standard errors around tabulated estimates with PUMS data as they take into account the complex structure of the survey sample. While working with replicate weights has traditionally been cumbersome for analysts, tidycensus with help from the <strong>survey</strong> <span class="citation">(<a href="references.html#ref-lumley2010" role="doc-biblioref">Lumley 2010</a>)</span> and <strong>srvyr</strong> <span class="citation">(<a href="references.html#ref-ellis2021" role="doc-biblioref">Freedman Ellis and Schneider 2021</a>)</span> R packages has integrated tools for handling replicate weights and correctly estimating standard errors when tabulating and modeling data. These workflows will be covered later in this chapter.</p>
<div id="pums-data-and-the-tidyverse" class="section level2" number="10.1">
<h2>
<span class="header-section-number">10.1</span> PUMS data and the tidyverse<a class="anchor" aria-label="anchor" href="#pums-data-and-the-tidyverse"><i class="fas fa-link"></i></a>
</h2>
<p>As discussed in Chapter <a href="introduction-to-census-microdata.html#introduction-to-census-microdata">9</a>, <code><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums()</a></code> automatically returns data with both household (<code>WGTP</code>) and person (<code>PWGTP</code>) weights. These weights can loosely be interpreted as the number of households - or persons - represented by each individual row in the PUMS data. Appropriate use of these weights columns is essential for tabulating accurate estimates of population characteristics with PUMS data. Fortunately, weighted tabulations work quite well within familiar tidyverse workflows, such as those covered in Chapter <a href="wrangling-census-data-with-tidyverse-tools.html#wrangling-census-data-with-tidyverse-tools">3</a>.</p>
<div id="basic-tabulation-of-weights-with-tidyverse-tools" class="section level3" number="10.1.1">
<h3>
<span class="header-section-number">10.1.1</span> Basic tabulation of weights with tidyverse tools<a class="anchor" aria-label="anchor" href="#basic-tabulation-of-weights-with-tidyverse-tools"><i class="fas fa-link"></i></a>
</h3>
<p>Let’s get some basic sample PUMS data from the 2015-2019 ACS for Mississippi with information on sex and age.</p>
<div class="sourceCode" id="cb336"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://walker-data.com/tidycensus/">tidycensus</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span>

<span class="va">ms_pums</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums</a></span><span class="op">(</span>
  variables <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"SEX"</span>, <span class="st">"AGEP"</span><span class="op">)</span>,
  state <span class="op">=</span> <span class="st">"MS"</span>,
  survey <span class="op">=</span> <span class="st">"acs5"</span>,
  year <span class="op">=</span> <span class="fl">2019</span>,
  recode <span class="op">=</span> <span class="cn">TRUE</span>
<span class="op">)</span></code></pre></div>
<p>Let’s take a quick look at our data:</p>
<div class="inline-table"><table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:glimpse-ms-pums">Table 10.1: </span>PUMS data for Mississippi
</caption>
<thead><tr>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
SERIALNO
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
SPORDER
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
WGTP
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
PWGTP
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
AGEP
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
ST
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
SEX
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
ST_label
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
SEX_label
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
2015000000200
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
53
</td>
<td style="text-align:left;">
28
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
Mississippi/MS
</td>
<td style="text-align:left;">
Female
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000000200
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
33
</td>
<td style="text-align:left;">
28
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
Mississippi/MS
</td>
<td style="text-align:left;">
Male
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000000200
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
32
</td>
<td style="text-align:left;">
28
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
Mississippi/MS
</td>
<td style="text-align:left;">
Male
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000000379
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
23
</td>
<td style="text-align:right;">
23
</td>
<td style="text-align:right;">
42
</td>
<td style="text-align:left;">
28
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
Mississippi/MS
</td>
<td style="text-align:left;">
Male
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000000379
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
23
</td>
<td style="text-align:right;">
22
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:left;">
28
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
Mississippi/MS
</td>
<td style="text-align:left;">
Female
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000000379
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
23
</td>
<td style="text-align:right;">
30
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:left;">
28
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
Mississippi/MS
</td>
<td style="text-align:left;">
Male
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000000379
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
23
</td>
<td style="text-align:right;">
30
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:left;">
28
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
Mississippi/MS
</td>
<td style="text-align:left;">
Male
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000000530
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
66
</td>
<td style="text-align:right;">
65
</td>
<td style="text-align:right;">
33
</td>
<td style="text-align:left;">
28
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
Mississippi/MS
</td>
<td style="text-align:left;">
Female
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000000530
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
66
</td>
<td style="text-align:right;">
67
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:left;">
28
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
Mississippi/MS
</td>
<td style="text-align:left;">
Male
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000000530
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
66
</td>
<td style="text-align:right;">
55
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
28
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
Mississippi/MS
</td>
<td style="text-align:left;">
Female
</td>
</tr>
</tbody>
</table></div>
<p>As we learned in Chapter <a href="analyzing-census-microdata.html#analyzing-census-microdata">10</a>, the number of people in Mississippi can be tabulated by summing over the person-weight column:</p>
<div class="sourceCode" id="cb337"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">ms_pums</span><span class="op">$</span><span class="va">PWGTP</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 2984418</code></pre>
<p>We can perform similar calculations with tidyverse tools. The <code>count()</code> function in the dplyr package performs a simple tabulation of your data. The optional <code>wt</code> argument in <code>count()</code> allows you to specify a weight column, which in this case will be our person-weight.</p>
<div class="sourceCode" id="cb339"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ms_pums</span> <span class="op">%&gt;%</span> <span class="fu">count</span><span class="op">(</span>wt <span class="op">=</span> <span class="va">PWGTP</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##         n
##     &lt;dbl&gt;
## 1 2984418</code></pre>
<p><code>count()</code> has the additional benefit of allowing for the specification of one our more columns that will be grouped and tabulated. For example, we could tabulate data by unique values of age and sex in Mississippi:</p>
<div class="sourceCode" id="cb341"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ms_pums</span> <span class="op">%&gt;%</span>
  <span class="fu">count</span><span class="op">(</span><span class="va">SEX_label</span>, <span class="va">AGEP</span>, wt <span class="op">=</span> <span class="va">PWGTP</span><span class="op">)</span> </code></pre></div>
<pre><code>## # A tibble: 186 × 3
##    SEX_label  AGEP     n
##    &lt;ord&gt;     &lt;dbl&gt; &lt;dbl&gt;
##  1 Male          0 18232
##  2 Male          1 19104
##  3 Male          2 18399
##  4 Male          3 18810
##  5 Male          4 20597
##  6 Male          5 18066
##  7 Male          6 20756
##  8 Male          7 20989
##  9 Male          8 20548
## 10 Male          9 21852
## # … with 176 more rows</code></pre>
<p>We can also perform more custom analyses, such as tabulating the number of people over age 65 by sex in Mississippi. This involves specifying a filter condition to retain rows for records with an age of 65 and up, then tabulating by sex.</p>
<div class="sourceCode" id="cb343"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ms_pums</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">AGEP</span> <span class="op">&gt;=</span> <span class="fl">65</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">count</span><span class="op">(</span><span class="va">SEX</span>, wt <span class="op">=</span> <span class="va">PWGTP</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 2
##   SEX        n
##   &lt;chr&gt;  &lt;dbl&gt;
## 1 1     200306
## 2 2     260737</code></pre>
<p>We can then use <code><a href="https://walker-data.com/tidycensus/reference/get_acs.html">get_acs()</a></code> to check our answer:</p>
<div class="sourceCode" id="cb345"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://walker-data.com/tidycensus/reference/get_acs.html">get_acs</a></span><span class="op">(</span>geography <span class="op">=</span> <span class="st">"state"</span>,
        state <span class="op">=</span> <span class="st">"MS"</span>,
        variables <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"DP05_0030"</span>, <span class="st">"DP05_0031"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
##   GEOID NAME        variable  estimate   moe
##   &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt;
## 1 28    Mississippi DP05_0030   200258   413
## 2 28    Mississippi DP05_0031   260764   468</code></pre>
<p>We notice that our tabulations are very close to the ACS estimates available in <code><a href="https://walker-data.com/tidycensus/reference/get_acs.html">get_acs()</a></code>, and well within the margin of error. When we are doing tabulations with microdata, it is important to remember that we are tabulating data based on a smaller subsample of information than is available to the aggregate ACS estimates. In turn, as the US Census Bureau reminds us <span class="citation">(<a href="references.html#ref-pums_readme" role="doc-biblioref">American Community Survey Office 2021</a>)</span>:</p>
<blockquote>
<p>Because PUMS data consist of a subset of the full ACS sample, tabulations from the ACS PUMS will not match those from published tables of ACS data.</p>
</blockquote>
<p>Analysts will often want to use PUMS data and the tabulated aggregate ACS data in tandem as appropriate, as each data type offers complimentary strengths. As the aggregate ACS data are based on a larger sample, its data aggregations will be preferable to those produced with PUMS data. However, PUMS data offer the ability to compute detailed cross-tabulations not available in aggregate ACS tables and to fit models of demographic relationships at the individual level. Examples of each follow in this chapter.</p>
</div>
<div id="group-wise-data-tabulation" class="section level3" number="10.1.2">
<h3>
<span class="header-section-number">10.1.2</span> Group-wise data tabulation<a class="anchor" aria-label="anchor" href="#group-wise-data-tabulation"><i class="fas fa-link"></i></a>
</h3>
<p>When combined with tidyverse tools as introduced in Chapter <a href="wrangling-census-data-with-tidyverse-tools.html#wrangling-census-data-with-tidyverse-tools">3</a>, PUMS data can produce highly detailed estimates not available in the regular aggregate ACS. The example below acquires data on rent burden, family type, and race/ethnicity to examine intersections between these variables for households in Mississippi. The <code>PUMA</code> variable is also included for use later in this chapter.</p>
<p>Our guiding research question is as follows: how does rent burden vary by race/ethnicity and household type for Mississippi households? This requires obtaining data on rent burden (gross rent as percentage of household income) with variable <code>GRPIP</code>; race and ethnicity with variables <code>RAC1P</code> and <code>HISP</code>; and household type with variable <code>HHT</code>. The <code>variables_filter</code> argument is used to filter the sample to only renter-occupied households paying cash rent, speeding download times.</p>
<div class="sourceCode" id="cb347"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">hh_variables</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"PUMA"</span>, <span class="st">"GRPIP"</span>, <span class="st">"RAC1P"</span>, 
                  <span class="st">"HISP"</span>, <span class="st">"HHT"</span><span class="op">)</span>

<span class="va">ms_hh_data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums</a></span><span class="op">(</span>
  variables <span class="op">=</span> <span class="va">hh_variables</span>, 
  state <span class="op">=</span> <span class="st">"MS"</span>,
  variables_filter <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>
    SPORDER <span class="op">=</span> <span class="fl">1</span>,
    TEN <span class="op">=</span> <span class="fl">3</span>
  <span class="op">)</span>,
  recode <span class="op">=</span> <span class="cn">TRUE</span>
<span class="op">)</span></code></pre></div>
<p>We can take a quick look at our data:</p>
<div class="inline-table"><table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:style-ms-hh">Table 10.2: </span>Household microdata for Mississippi
</caption>
<thead><tr>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
SERIALNO
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
SPORDER
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
WGTP
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
PWGTP
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
GRPIP
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
PUMA
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
ST
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
TEN
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
HHT
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
HISP
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
RAC1P
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
ST_label
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
TEN_label
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
HHT_label
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
HISP_label
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
RAC1P_label
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
2015000004656
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
64
</td>
<td style="text-align:right;">
64
</td>
<td style="text-align:right;">
46
</td>
<td style="text-align:left;">
01500
</td>
<td style="text-align:left;">
28
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
4
</td>
<td style="text-align:left;">
01
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
Mississippi/MS
</td>
<td style="text-align:left;">
Rented
</td>
<td style="text-align:left;">
Nonfamily household: Male householder: Living alone
</td>
<td style="text-align:left;">
Not Spanish/Hispanic/Latino
</td>
<td style="text-align:left;">
Black or African American alone
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000005252
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
38
</td>
<td style="text-align:left;">
00400
</td>
<td style="text-align:left;">
28
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
7
</td>
<td style="text-align:left;">
01
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
Mississippi/MS
</td>
<td style="text-align:left;">
Rented
</td>
<td style="text-align:left;">
Nonfamily household: Female householder: Not living alone
</td>
<td style="text-align:left;">
Not Spanish/Hispanic/Latino
</td>
<td style="text-align:left;">
White alone
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000006468
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
47
</td>
<td style="text-align:left;">
00500
</td>
<td style="text-align:left;">
28
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
01
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
Mississippi/MS
</td>
<td style="text-align:left;">
Rented
</td>
<td style="text-align:left;">
Married couple household
</td>
<td style="text-align:left;">
Not Spanish/Hispanic/Latino
</td>
<td style="text-align:left;">
Black or African American alone
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000006891
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
33
</td>
<td style="text-align:right;">
32
</td>
<td style="text-align:right;">
80
</td>
<td style="text-align:left;">
02000
</td>
<td style="text-align:left;">
28
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
01
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
Mississippi/MS
</td>
<td style="text-align:left;">
Rented
</td>
<td style="text-align:left;">
Other family household: Female householder, no spouse present
</td>
<td style="text-align:left;">
Not Spanish/Hispanic/Latino
</td>
<td style="text-align:left;">
Black or African American alone
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000007641
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
36
</td>
<td style="text-align:left;">
01100
</td>
<td style="text-align:left;">
28
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
01
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
Mississippi/MS
</td>
<td style="text-align:left;">
Rented
</td>
<td style="text-align:left;">
Nonfamily household: Male householder: Not living alone
</td>
<td style="text-align:left;">
Not Spanish/Hispanic/Latino
</td>
<td style="text-align:left;">
Black or African American alone
</td>
</tr>
</tbody>
</table></div>
<p>To analyze rent burdens with respect to the marital status and race/ethnicity of the householder, it will be useful to do some additional recoding using <strong>dplyr</strong>’s <code>case_when()</code> function. A new <code>race_ethnicity</code> column will identify householders by general categories, and a <code>married</code> column will identify whether or not the household is a married-couple household.</p>
<div class="sourceCode" id="cb348"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ms_hh_recoded</span> <span class="op">&lt;-</span> <span class="va">ms_hh_data</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>
    race_ethnicity <span class="op">=</span> <span class="fu">case_when</span><span class="op">(</span>
      <span class="va">HISP</span> <span class="op">!=</span> <span class="st">"01"</span> <span class="op">~</span> <span class="st">"Hispanic"</span>,
      <span class="va">HISP</span> <span class="op">==</span> <span class="st">"01"</span> <span class="op">&amp;</span> <span class="va">RAC1P</span> <span class="op">==</span> <span class="st">"1"</span> <span class="op">~</span> <span class="st">"White"</span>,
      <span class="va">HISP</span> <span class="op">==</span> <span class="st">"01"</span> <span class="op">&amp;</span> <span class="va">RAC1P</span> <span class="op">==</span> <span class="st">"2"</span> <span class="op">~</span> <span class="st">"Black"</span>,
      <span class="cn">TRUE</span> <span class="op">~</span> <span class="st">"Other"</span>
    <span class="op">)</span>,
    married <span class="op">=</span> <span class="fu">case_when</span><span class="op">(</span>
      <span class="va">HHT</span> <span class="op">==</span> <span class="st">"1"</span> <span class="op">~</span> <span class="st">"Married"</span>,
      <span class="cn">TRUE</span> <span class="op">~</span> <span class="st">"Not married"</span>
    <span class="op">)</span>
  <span class="op">)</span></code></pre></div>
<p>This information can then be summarized with respect to the household weight variable <code>WGTP</code> and the rent burden variable <code>GRPIP</code> within a <code>group_by() %&gt;% summarize()</code> workflow. The dataset is filtered to only non-Hispanic white, non-Hispanic Black, and Hispanic householders to focus on those groups, then grouped by race/ethnicity and marital status. Within the <code><a href="http://gdfe.co/srvyr/reference/summarise.html">summarize()</a></code> call, the percentage of each subgroup paying 40 percent or more of their household incomes in rent is calculated by summing over the household weight column <code>WGTP</code>, but filtering for households with rent burdens of 40 percent or more in the numerator.</p>
<div class="sourceCode" id="cb349"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ms_hh_summary</span> <span class="op">&lt;-</span> <span class="va">ms_hh_recoded</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">race_ethnicity</span> <span class="op">!=</span> <span class="st">"Other"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">race_ethnicity</span>, <span class="va">married</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">summarize</span><span class="op">(</span>
    prop_above_40 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">WGTP</span><span class="op">[</span><span class="va">GRPIP</span> <span class="op">&gt;=</span> <span class="fl">40</span><span class="op">]</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">WGTP</span><span class="op">)</span>
  <span class="op">)</span></code></pre></div>
<p>We can now check our result:</p>
<div class="inline-table"><table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:ms-hh-summary-show">Table 10.3: </span>Tabulated PUMS data for Mississippi
</caption>
<thead><tr>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
race_ethnicity
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
married
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
prop_above_40
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Black
</td>
<td style="text-align:left;">
Married
</td>
<td style="text-align:right;">
0.1821176
</td>
</tr>
<tr>
<td style="text-align:left;">
Black
</td>
<td style="text-align:left;">
Not married
</td>
<td style="text-align:right;">
0.4167467
</td>
</tr>
<tr>
<td style="text-align:left;">
Hispanic
</td>
<td style="text-align:left;">
Married
</td>
<td style="text-align:right;">
0.1723502
</td>
</tr>
<tr>
<td style="text-align:left;">
Hispanic
</td>
<td style="text-align:left;">
Not married
</td>
<td style="text-align:right;">
0.3006062
</td>
</tr>
<tr>
<td style="text-align:left;">
White
</td>
<td style="text-align:left;">
Married
</td>
<td style="text-align:right;">
0.1349339
</td>
</tr>
<tr>
<td style="text-align:left;">
White
</td>
<td style="text-align:left;">
Not married
</td>
<td style="text-align:right;">
0.3299732
</td>
</tr>
</tbody>
</table></div>
<p>The demographic group in this example with the largest rent burden is Black, Not married; nearly 42 percent of households in this group pay over 40 percent of their incomes in gross rent. The least rent-burdened group is White, Married, with a value under 14 percent. For each of the three racial/ethnic groups, there is a distinctive financial advantage for married-couple households over non-married households; this is particularly pronounced for Black householders.</p>
</div>
</div>
<div id="mapping-pums-data" class="section level2" number="10.2">
<h2>
<span class="header-section-number">10.2</span> Mapping PUMS data<a class="anchor" aria-label="anchor" href="#mapping-pums-data"><i class="fas fa-link"></i></a>
</h2>
<p>In the previous example, we see that rent burdens for Black, unmarried households are particularly acute in Mississippi. A follow-up question may involve an examination of how this trend varies geographically. As discussed in the previous chapter, the most granular geography available in the PUMS data is the PUMA, which generally includes 100,000-200,000 people. PUMA geographies are available in the <strong>tigris</strong> package with the function <code><a href="https://rdrr.io/pkg/tigris/man/pumas.html">pumas()</a></code>.</p>
<div class="sourceCode" id="cb350"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/walkerke/tigris">tigris</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/mtennekes/tmap">tmap</a></span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/options.html">options</a></span><span class="op">(</span>tigris_use_cache <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>

<span class="va">ms_pumas</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/tigris/man/pumas.html">pumas</a></span><span class="op">(</span><span class="st">"MS"</span>, cb <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>

<span class="fu"><a href="https://r-spatial.github.io/sf/reference/plot.html">plot</a></span><span class="op">(</span><span class="va">ms_pumas</span><span class="op">$</span><span class="va">geometry</span><span class="op">)</span></code></pre></div>
<div class="figure">
<span style="display:block;" id="fig:join-ms-data"></span>
<img src="10-modeling-microdata_files/figure-html/join-ms-data-1.png" alt="Basic plot of PUMAs in Mississippi" width="100%"><p class="caption">
Figure 10.1: Basic plot of PUMAs in Mississippi
</p>
</div>
<p>A geographical visualization of rent burdens in Mississippi requires a slight adaptation of the above code. Instead of returning a comparative table, the dataset should also be grouped by the <code>PUMA</code> column then filtered for the combination of variables that represent the group the analyst wants to visualize. In this case, the focus is on unmarried Black households by PUMA.</p>
<div class="sourceCode" id="cb351"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ms_data_for_map</span> <span class="op">&lt;-</span> <span class="va">ms_hh_recoded</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">race_ethnicity</span>, <span class="va">married</span>, <span class="va">PUMA</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">summarize</span><span class="op">(</span>
    percent_above_40 <span class="op">=</span> <span class="fl">100</span> <span class="op">*</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">WGTP</span><span class="op">[</span><span class="va">GRPIP</span> <span class="op">&gt;=</span> <span class="fl">40</span><span class="op">]</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">WGTP</span><span class="op">)</span><span class="op">)</span>
  <span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">race_ethnicity</span> <span class="op">==</span> <span class="st">"Black"</span>,
         <span class="va">married</span> <span class="op">==</span> <span class="st">"Not married"</span><span class="op">)</span></code></pre></div>
<p>The output dataset has one row per PUMA and is suitable for joining to the spatial dataset for visualization.</p>
<div class="sourceCode" id="cb352"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/mtennekes/tmap">tmap</a></span><span class="op">)</span>

<span class="va">joined_pumas</span> <span class="op">&lt;-</span> <span class="va">ms_pumas</span> <span class="op">%&gt;%</span>
  <span class="fu">left_join</span><span class="op">(</span><span class="va">ms_data_for_map</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"PUMACE10"</span> <span class="op">=</span> <span class="st">"PUMA"</span><span class="op">)</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">joined_pumas</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_polygons</a></span><span class="op">(</span>col <span class="op">=</span> <span class="st">"percent_above_40"</span>, 
              palette <span class="op">=</span> <span class="st">"Reds"</span>,
              title <span class="op">=</span> <span class="st">"% rent-burdened\nunmarried Black households"</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_layout.html">tm_layout</a></span><span class="op">(</span>legend.outside <span class="op">=</span> <span class="cn">TRUE</span>,
            legend.outside.position <span class="op">=</span> <span class="st">"right"</span><span class="op">)</span></code></pre></div>
<div class="figure">
<span style="display:block;" id="fig:ms-pums-map"></span>
<img src="10-modeling-microdata_files/figure-html/ms-pums-map-1.png" alt="Map of rent-burdened unmarried Black household share by PUMA in Mississippi" width="100%"><p class="caption">
Figure 10.2: Map of rent-burdened unmarried Black household share by PUMA in Mississippi
</p>
</div>
<p>The map illustrates geographic variations in our indicator of interest. In particular, unmarried Black households are particularly rent-burdened along the Gulf Coast, with over half of households paying at least 40 percent of their household incomes in gross rent. The least rent-burdened areas for this demographic group are in the suburban PUMAs around Jackson.</p>
</div>
<div id="survey-design-and-the-acs-pums" class="section level2" number="10.3">
<h2>
<span class="header-section-number">10.3</span> Survey design and the ACS PUMS<a class="anchor" aria-label="anchor" href="#survey-design-and-the-acs-pums"><i class="fas fa-link"></i></a>
</h2>
<p>As earlier chapters have addressed, the American Community Survey is based on a <em>sample</em> of the US population and in turn subject to sampling error. This becomes particularly acute when dealing with small sub-populations like those explored at the PUMA level in the previous section. Given that PUMS data are individual-level records and not aggregates, standard errors and in turn margins of error must be computed by the analyst. Doing so correctly requires accounting for the complex sample design of the ACS. Fortunately, <strong>tidycensus</strong> with help from the <strong>survey</strong> and <strong>srvyr</strong> packages includes tools to assist with these tasks.</p>
<div id="getting-replicate-weights" class="section level3" number="10.3.1">
<h3>
<span class="header-section-number">10.3.1</span> Getting replicate weights<a class="anchor" aria-label="anchor" href="#getting-replicate-weights"><i class="fas fa-link"></i></a>
</h3>
<p>The Census Bureau recommends using the <em>Successive Difference Replication</em> method to compute standard errors around derived estimates from PUMS data. To calculate standard errors, the Census Bureau publishes 80 “replicate weights” for each observation, representing either person (PWGTP1 through PWGTP80) or household (WGTP1 through WGTP80) weights <span class="citation">(<a href="references.html#ref-pums_readme" role="doc-biblioref">American Community Survey Office 2021</a>)</span>. The formula for computing the standard error <span class="math inline">\(SE\)</span> for a derived PUMS estimate <span class="math inline">\(x\)</span> is as follows:</p>
<p><span class="math display">\[
SE(x) = \sqrt{\frac{4}{80}\sum\limits_{r=1}^{80}(x_r-x)^2 }
\]</span></p>
<p>where <span class="math inline">\(x\)</span> is the PUMS estimate and <span class="math inline">\(x_r\)</span> is the rth weighted estimate.</p>
<p>With respect to SDR standard errors, the PUMS documentation acknowledges (p. 12),</p>
<blockquote>
<p>Successive Difference Replication (SDR) standard errors and margins of error are expected to be more accurate than generalized variance formulas (GVF) standard errorsand margins of error, although they may be more inconvenient for some users to calculate.</p>
</blockquote>
<p>The “inconvenience” is generally due to the need to download 80 additional weighting variables and prepare the equation written above. The <code>rep_weights</code> parameter in <code><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums()</a></code> makes it easier for users to retrieve the replicate weights variables without having to request all 80 directly. In a call to <code><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums()</a></code>, an analyst can use <code>rep_weights = "person"</code> for person-weights, <code>"housing"</code> for household weights, or <code>"both"</code> to get both sets.</p>
<p>The code below re-downloads the Mississippi rent burden dataset used above, but with household replicate weights included.</p>
<div class="sourceCode" id="cb353"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ms_hh_replicate</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums</a></span><span class="op">(</span>
  variables <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"TEN"</span>, <span class="va">hh_variables</span><span class="op">)</span>, 
  state <span class="op">=</span> <span class="st">"MS"</span>,
  recode <span class="op">=</span> <span class="cn">TRUE</span>,
  variables_filter <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>
    SPORDER <span class="op">=</span> <span class="fl">1</span>
  <span class="op">)</span>,
  rep_weights <span class="op">=</span> <span class="st">"housing"</span>
<span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb354"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">ms_hh_replicate</span><span class="op">)</span></code></pre></div>
<pre><code>##  [1] "SERIALNO"    "SPORDER"     "GRPIP"       "PUMA"        "ST"         
##  [6] "TEN"         "HHT"         "HISP"        "RAC1P"       "ST_label"   
## [11] "TEN_label"   "HHT_label"   "HISP_label"  "RAC1P_label" "WGTP"       
## [16] "PWGTP"       "WGTP1"       "WGTP2"       "WGTP3"       "WGTP4"      
## [21] "WGTP5"       "WGTP6"       "WGTP7"       "WGTP8"       "WGTP9"      
## [26] "WGTP10"      "WGTP11"      "WGTP12"      "WGTP13"      "WGTP14"     
## [31] "WGTP15"      "WGTP16"      "WGTP17"      "WGTP18"      "WGTP19"     
## [36] "WGTP20"      "WGTP21"      "WGTP22"      "WGTP23"      "WGTP24"     
## [41] "WGTP25"      "WGTP26"      "WGTP27"      "WGTP28"      "WGTP29"     
## [46] "WGTP30"      "WGTP31"      "WGTP32"      "WGTP33"      "WGTP34"     
## [51] "WGTP35"      "WGTP36"      "WGTP37"      "WGTP38"      "WGTP39"     
## [56] "WGTP40"      "WGTP41"      "WGTP42"      "WGTP43"      "WGTP44"     
## [61] "WGTP45"      "WGTP46"      "WGTP47"      "WGTP48"      "WGTP49"     
## [66] "WGTP50"      "WGTP51"      "WGTP52"      "WGTP53"      "WGTP54"     
## [71] "WGTP55"      "WGTP56"      "WGTP57"      "WGTP58"      "WGTP59"     
## [76] "WGTP60"      "WGTP61"      "WGTP62"      "WGTP63"      "WGTP64"     
## [81] "WGTP65"      "WGTP66"      "WGTP67"      "WGTP68"      "WGTP69"     
## [86] "WGTP70"      "WGTP71"      "WGTP72"      "WGTP73"      "WGTP74"     
## [91] "WGTP75"      "WGTP76"      "WGTP77"      "WGTP78"      "WGTP79"     
## [96] "WGTP80"</code></pre>
<p>All 80 household replicate weights are included in the dataset. A key distinction in the above code, however, is that the housing tenure variable <code>TEN</code> is not included in the <code>variables_filter</code> argument, instead returning the full sample of households in Mississippi. This is because standard error estimation for complex survey samples requires special methods for <em>subpopulations</em>, which will be covered below.</p>
</div>
<div id="creating-a-survey-object" class="section level3" number="10.3.2">
<h3>
<span class="header-section-number">10.3.2</span> Creating a survey object<a class="anchor" aria-label="anchor" href="#creating-a-survey-object"><i class="fas fa-link"></i></a>
</h3>
<p>With replicate weights in hand, analysts can turn to a suite of tools in R for handling complex survey samples. The <strong>survey</strong> package <span class="citation">(<a href="references.html#ref-lumley2010" role="doc-biblioref">Lumley 2010</a>)</span> is the standard for handling these types of datasets in R. The more recent <strong>srvyr</strong> package <span class="citation">(<a href="references.html#ref-ellis2021" role="doc-biblioref">Freedman Ellis and Schneider 2021</a>)</span> wraps <strong>survey</strong> to allow the use of tidyverse functions on survey objects. Both packages return a <code>survey</code> class object that intelligently calculates standard errors when data are tabulated with appropriate functions. <strong>tidycensus</strong> includes a function, <code><a href="https://walker-data.com/tidycensus/reference/to_survey.html">to_survey()</a></code>, to convert ACS microdata to <strong>survey</strong> or <strong>srvyr</strong> objects in a way that incorporates the recommended formula for SDR standard error calculation with replicate weights.</p>
<div class="sourceCode" id="cb356"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://r-survey.r-forge.r-project.org/survey/">survey</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://gdfe.co/srvyr/">srvyr</a></span><span class="op">)</span>

<span class="va">ms_hh_svy</span> <span class="op">&lt;-</span> <span class="va">ms_hh_replicate</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://walker-data.com/tidycensus/reference/to_survey.html">to_survey</a></span><span class="op">(</span>type <span class="op">=</span> <span class="st">"housing"</span>, 
            design <span class="op">=</span> <span class="st">"rep_weights"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="http://gdfe.co/srvyr/reference/dplyr_single.html">filter</a></span><span class="op">(</span><span class="va">TEN</span> <span class="op">==</span> <span class="fl">3</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/base/class.html">class</a></span><span class="op">(</span><span class="va">ms_hh_svy</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "tbl_svy"       "svyrep.design"</code></pre>
<p>The <code><a href="https://walker-data.com/tidycensus/reference/to_survey.html">to_survey()</a></code> function returns the original dataset as an object of class <code>tbl_svy</code> and <code>svyrep.design</code> with minimal hassle.</p>
<p>Note the use of <code><a href="http://gdfe.co/srvyr/reference/dplyr_single.html">filter()</a></code> after converting the replicate weights dataset to a survey object to subset the data to only renter-occupied households paying cash rent. When computing standard errors for derived estimates using complex survey samples, it is necessary to take the entire structure of the sample into account. In turn, it is important to <em>first</em> convert the dataset into a survey object <em>and then</em> identify the “subpopulation” for which the model will be fit.</p>
<p>For analysis of subpopulations, <code><a href="http://gdfe.co/srvyr/reference/dplyr_single.html">srvyr::filter()</a></code> works like <code>survey::subset()</code> for appropriate standard error estimation. This data structure will then be taken into account when calculating standard errors.</p>
</div>
<div id="calculating-estimates-and-errors-with-srvyr" class="section level3" number="10.3.3">
<h3>
<span class="header-section-number">10.3.3</span> Calculating estimates and errors with srvyr<a class="anchor" aria-label="anchor" href="#calculating-estimates-and-errors-with-srvyr"><i class="fas fa-link"></i></a>
</h3>
<p>srvyr’s <code>survey_*()</code> family of functions automatically calculates standard errors around tabulated estimates using tidyverse-equivalent functions. For example, analogous to the use of <code>count()</code> to tabulate weighted data, <code><a href="http://gdfe.co/srvyr/reference/survey_tally.html">survey_count()</a></code> will do the same for a survey object but will also return appropriately-calculated standard errors.</p>
<div class="sourceCode" id="cb358"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ms_hh_svy</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="http://gdfe.co/srvyr/reference/survey_tally.html">survey_count</a></span><span class="op">(</span><span class="va">PUMA</span>, <span class="va">HHT_label</span><span class="op">)</span></code></pre></div>
<div class="inline-table"><table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:ms-svy-show">Table 10.4: </span>Tabulated PUMS data for household types in Mississippi by PUMA with standard errors
</caption>
<thead><tr>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
PUMA
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
HHT_label
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
n
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
n_se
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
00100
</td>
<td style="text-align:left;">
Married couple household
</td>
<td style="text-align:right;">
5067
</td>
<td style="text-align:right;">
406.0426
</td>
</tr>
<tr>
<td style="text-align:left;">
00100
</td>
<td style="text-align:left;">
Other family household: Male householder, no spouse present
</td>
<td style="text-align:right;">
1342
</td>
<td style="text-align:right;">
207.5266
</td>
</tr>
<tr>
<td style="text-align:left;">
00100
</td>
<td style="text-align:left;">
Other family household: Female householder, no spouse present
</td>
<td style="text-align:right;">
3657
</td>
<td style="text-align:right;">
321.1575
</td>
</tr>
<tr>
<td style="text-align:left;">
00100
</td>
<td style="text-align:left;">
Nonfamily household: Male householder: Living alone
</td>
<td style="text-align:right;">
2042
</td>
<td style="text-align:right;">
236.2904
</td>
</tr>
<tr>
<td style="text-align:left;">
00100
</td>
<td style="text-align:left;">
Nonfamily household: Male householder: Not living alone
</td>
<td style="text-align:right;">
796
</td>
<td style="text-align:right;">
157.2994
</td>
</tr>
</tbody>
</table></div>
<p>The <code><a href="http://gdfe.co/srvyr/reference/survey_tally.html">survey_count()</a></code> function returns tabulations for each household type by PUMA in Mississippi along with the estimate’s standard error. The <strong>srvyr</strong> package can also accommodate more complex workflows. Below is an adaptation of the rent burden analysis computed above, but using the <strong>srvyr</strong> function <code><a href="http://gdfe.co/srvyr/reference/survey_mean.html">survey_mean()</a></code>.</p>
<div class="sourceCode" id="cb359"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ms_svy_summary</span> <span class="op">&lt;-</span> <span class="va">ms_hh_svy</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="http://gdfe.co/srvyr/reference/dplyr_single.html">mutate</a></span><span class="op">(</span>
    race_ethnicity <span class="op">=</span> <span class="fu">case_when</span><span class="op">(</span>
      <span class="va">HISP</span> <span class="op">!=</span> <span class="st">"01"</span> <span class="op">~</span> <span class="st">"Hispanic"</span>,
      <span class="va">HISP</span> <span class="op">==</span> <span class="st">"01"</span> <span class="op">&amp;</span> <span class="va">RAC1P</span> <span class="op">==</span> <span class="st">"1"</span> <span class="op">~</span> <span class="st">"White"</span>,
      <span class="va">HISP</span> <span class="op">==</span> <span class="st">"01"</span> <span class="op">&amp;</span> <span class="va">RAC1P</span> <span class="op">==</span> <span class="st">"2"</span> <span class="op">~</span> <span class="st">"Black"</span>,
      <span class="cn">TRUE</span> <span class="op">~</span> <span class="st">"Other"</span>
    <span class="op">)</span>,
    married <span class="op">=</span> <span class="fu">case_when</span><span class="op">(</span>
      <span class="va">HHT</span> <span class="op">==</span> <span class="st">"1"</span> <span class="op">~</span> <span class="st">"Married"</span>,
      <span class="cn">TRUE</span> <span class="op">~</span> <span class="st">"Not married"</span>
    <span class="op">)</span>,
    above_40 <span class="op">=</span> <span class="va">GRPIP</span> <span class="op">&gt;=</span> <span class="fl">40</span>
  <span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="http://gdfe.co/srvyr/reference/dplyr_single.html">filter</a></span><span class="op">(</span><span class="va">race_ethnicity</span> <span class="op">!=</span> <span class="st">"Other"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="http://gdfe.co/srvyr/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">race_ethnicity</span>, <span class="va">married</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="http://gdfe.co/srvyr/reference/summarise.html">summarize</a></span><span class="op">(</span>
    prop_above_40 <span class="op">=</span> <span class="fu"><a href="http://gdfe.co/srvyr/reference/survey_mean.html">survey_mean</a></span><span class="op">(</span><span class="va">above_40</span><span class="op">)</span>
  <span class="op">)</span>  </code></pre></div>
<div class="inline-table"><table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:svy-summary-show">Table 10.5: </span>Derived estimates for PUMS data with standard errors
</caption>
<thead><tr>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
race_ethnicity
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
married
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
prop_above_40
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
prop_above_40_se
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Black
</td>
<td style="text-align:left;">
Married
</td>
<td style="text-align:right;">
0.1821176
</td>
<td style="text-align:right;">
0.0133532
</td>
</tr>
<tr>
<td style="text-align:left;">
Black
</td>
<td style="text-align:left;">
Not married
</td>
<td style="text-align:right;">
0.4167467
</td>
<td style="text-align:right;">
0.0065519
</td>
</tr>
<tr>
<td style="text-align:left;">
Hispanic
</td>
<td style="text-align:left;">
Married
</td>
<td style="text-align:right;">
0.1723502
</td>
<td style="text-align:right;">
0.0323387
</td>
</tr>
<tr>
<td style="text-align:left;">
Hispanic
</td>
<td style="text-align:left;">
Not married
</td>
<td style="text-align:right;">
0.3006062
</td>
<td style="text-align:right;">
0.0292211
</td>
</tr>
<tr>
<td style="text-align:left;">
White
</td>
<td style="text-align:left;">
Married
</td>
<td style="text-align:right;">
0.1349339
</td>
<td style="text-align:right;">
0.0100294
</td>
</tr>
<tr>
<td style="text-align:left;">
White
</td>
<td style="text-align:left;">
Not married
</td>
<td style="text-align:right;">
0.3299732
</td>
<td style="text-align:right;">
0.0078680
</td>
</tr>
</tbody>
</table></div>
<p>The derived estimates are the same as before, but the <strong>srvyr</strong> workflow also returns standard errors.</p>
</div>
<div id="converting-standard-errors-to-margins-of-error" class="section level3" number="10.3.4">
<h3>
<span class="header-section-number">10.3.4</span> Converting standard errors to margins of error<a class="anchor" aria-label="anchor" href="#converting-standard-errors-to-margins-of-error"><i class="fas fa-link"></i></a>
</h3>
<p>To convert standard errors to <em>margins of error</em> around the derived PUMS estimates, analysts should multiply the standard errors by the following coefficients:</p>
<ul>
<li><p>90 percent confidence level: 1.645</p></li>
<li><p>95 percent confidence level: 1.96</p></li>
<li><p>99 percent confidence level: 2.56</p></li>
</ul>
<p>Computing margins of error around derived ACS estimates from PUMS data allows for familiar visualization of uncertainty in the ACS as shown earlier in this book. The example below calculates margins of error at a 90 percent confidence level for the rent burden estimates for Mississippi, then draws a margin of error plot as illustrated in Section <a href="exploring-us-census-data-with-visualization.html#visualizing-margins-of-error">4.2</a>.</p>
<div class="sourceCode" id="cb360"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ms_svy_summary_moe</span> <span class="op">&lt;-</span> <span class="va">ms_svy_summary</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="http://gdfe.co/srvyr/reference/dplyr_single.html">mutate</a></span><span class="op">(</span>prop_above_40_moe <span class="op">=</span> <span class="va">prop_above_40_se</span> <span class="op">*</span> <span class="fl">1.645</span>,
         label <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="va">race_ethnicity</span>, <span class="va">married</span>, sep <span class="op">=</span> <span class="st">", "</span><span class="op">)</span><span class="op">)</span> 

<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">ms_svy_summary_moe</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">prop_above_40</span>, 
                               y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/reorder.factor.html">reorder</a></span><span class="op">(</span><span class="va">label</span>, 
                                           <span class="va">prop_above_40</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_errorbarh.html">geom_errorbarh</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>xmin <span class="op">=</span> <span class="va">prop_above_40</span> <span class="op">-</span> <span class="va">prop_above_40_moe</span>, 
                     xmax <span class="op">=</span> <span class="va">prop_above_40</span> <span class="op">+</span> <span class="va">prop_above_40_moe</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">3</span>, color <span class="op">=</span> <span class="st">"navy"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Rent burdened-households in Mississippi"</span>,
       x <span class="op">=</span> <span class="st">"2015-2019 ACS estimate (from PUMS data)"</span>,
       y <span class="op">=</span> <span class="st">""</span>,
       caption <span class="op">=</span> <span class="st">"Rent-burdened defined when gross rent is 40 percent or more\nof household income. Error bars represent a 90 percent confidence level."</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="va"><a href="https://scales.r-lib.org/reference/label_percent.html">percent</a></span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_grey</a></span><span class="op">(</span>base_size <span class="op">=</span> <span class="fl">12</span><span class="op">)</span></code></pre></div>
<div class="figure">
<span style="display:block;" id="fig:svy-plot"></span>
<img src="10-modeling-microdata_files/figure-html/svy-plot-1.png" alt="Margin of error plot for derived PUMS estimates" width="100%"><p class="caption">
Figure 10.3: Margin of error plot for derived PUMS estimates
</p>
</div>
<p>The plot effectively represents the uncertainty associated with estimates for the relatively small Hispanic population in Mississippi.</p>
</div>
</div>
<div id="modeling-with-pums-data" class="section level2" number="10.4">
<h2>
<span class="header-section-number">10.4</span> Modeling with PUMS data<a class="anchor" aria-label="anchor" href="#modeling-with-pums-data"><i class="fas fa-link"></i></a>
</h2>
<p>The rich complexity of demographic data available in the PUMS samples allow for the estimation of statistical models to study a wide range of social processes. Like the tabulation of summary statistics with PUMS data, however, statistical models that use complex survey samples require special methods. Fortunately, these methods are incorporated into the <strong>srvyr</strong> and <strong>survey</strong> packages.</p>
<p>Before estimating the model, data should be acquired with <code><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums()</a></code> along with appropriate replicate weights. The example below will model whether or not an individual in the labor force aged between 25 and 49 changed residences in the past year as a function of educational attainment, wages, age, class of worker, and family status in Rhode Island.</p>
<p>Even though our model will focus on the population in the labor force aged 25 to 49, <code>variables_filter</code> should not be used here as the full dataset is needed for appropriate model estimation. This will be addressed in the next section.</p>
<div id="data-preparation" class="section level3" number="10.4.1">
<h3>
<span class="header-section-number">10.4.1</span> Data preparation<a class="anchor" aria-label="anchor" href="#data-preparation"><i class="fas fa-link"></i></a>
</h3>
<p>Similar to Section <a href="modeling-us-census-data.html#feature-engineering">8.2.3</a>, we will perform some feature engineering before fitting the model. This largely involves recoding both the outcome variable and the predictors to more general categories to assist with ease of interpretation. As with other recoding workflows in this book, <code>case_when()</code> collapses the categories.</p>
<div class="sourceCode" id="cb361"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ri_pums_recoded</span> <span class="op">&lt;-</span> <span class="va">ri_pums_to_model</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="http://gdfe.co/srvyr/reference/dplyr_single.html">mutate</a></span><span class="op">(</span>
    emp_type <span class="op">=</span> <span class="fu">case_when</span><span class="op">(</span>
      <span class="va">COW</span> <span class="op">%in%</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"1"</span>, <span class="st">"2"</span><span class="op">)</span> <span class="op">~</span> <span class="st">"private"</span>,
      <span class="va">COW</span> <span class="op">%in%</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"3"</span>, <span class="st">"4"</span>, <span class="st">"5"</span><span class="op">)</span> <span class="op">~</span> <span class="st">"public"</span>,
      <span class="cn">TRUE</span> <span class="op">~</span> <span class="st">"self"</span>
      <span class="op">)</span>, 
    child <span class="op">=</span> <span class="fu">case_when</span><span class="op">(</span>
      <span class="va">NOC</span> <span class="op">&gt;</span> <span class="fl">0</span> <span class="op">~</span> <span class="st">"yes"</span>,
      <span class="cn">TRUE</span> <span class="op">~</span> <span class="st">"no"</span>
    <span class="op">)</span>,
    married <span class="op">=</span> <span class="fu">case_when</span><span class="op">(</span>
      <span class="va">MAR</span> <span class="op">==</span> <span class="fl">1</span> <span class="op">~</span> <span class="st">"yes"</span>,
      <span class="cn">TRUE</span> <span class="op">~</span> <span class="st">"no"</span>
    <span class="op">)</span>,
    college <span class="op">=</span> <span class="fu">case_when</span><span class="op">(</span>
      <span class="va">SCHL</span> <span class="op">%in%</span> <span class="fu"><a href="https://rdrr.io/r/base/character.html">as.character</a></span><span class="op">(</span><span class="fl">21</span><span class="op">:</span><span class="fl">24</span><span class="op">)</span> <span class="op">~</span> <span class="st">"yes"</span>,
      <span class="cn">TRUE</span> <span class="op">~</span> <span class="st">"no"</span>
    <span class="op">)</span>,
    sex <span class="op">=</span> <span class="fu">case_when</span><span class="op">(</span>
      <span class="va">SEX</span> <span class="op">==</span> <span class="fl">2</span> <span class="op">~</span> <span class="st">"female"</span>,
      <span class="cn">TRUE</span> <span class="op">~</span> <span class="st">"male"</span>
    <span class="op">)</span>,
    migrated <span class="op">=</span> <span class="fu">case_when</span><span class="op">(</span>
      <span class="va">MIG</span> <span class="op">==</span> <span class="fl">1</span> <span class="op">~</span> <span class="fl">0</span>,
      <span class="cn">TRUE</span> <span class="op">~</span> <span class="fl">1</span>
    <span class="op">)</span>
  <span class="op">)</span></code></pre></div>
<p>Given that we will be estimating a logistic regression model with a binary outcome (whether or not an individual is a migrant, <code>migrated</code> is coded as either 0 or 1. The other recoded variables will be used as <em>categorical predictors</em>, in which parameter estimates refer to probabilities of having migrated relative to a reference category (e.g. college graduates relative to individuals who have not graduated college).</p>
<p>In the next step, the subpopulation for which the model will be estimated is identified using <code><a href="http://gdfe.co/srvyr/reference/dplyr_single.html">filter()</a></code>. We will focus on individuals aged 25 to 49 who are employed and earned wages in the past year.</p>
<div class="sourceCode" id="cb362"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ri_model_svy</span> <span class="op">&lt;-</span> <span class="va">ri_pums_recoded</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://walker-data.com/tidycensus/reference/to_survey.html">to_survey</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="http://gdfe.co/srvyr/reference/dplyr_single.html">filter</a></span><span class="op">(</span>
    <span class="va">ESR</span> <span class="op">==</span> <span class="fl">1</span>,   <span class="co"># civilian employed</span>
    <span class="va">WAGP</span> <span class="op">&gt;</span> <span class="fl">0</span>,   <span class="co"># earned wages last year</span>
    <span class="va">AGEP</span> <span class="op">&gt;=</span> <span class="fl">25</span>,
    <span class="va">AGEP</span> <span class="op">&lt;=</span> <span class="fl">49</span>
  <span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="http://gdfe.co/srvyr/reference/dplyr_single.html">rename</a></span><span class="op">(</span>age <span class="op">=</span> <span class="va">AGEP</span>, wages <span class="op">=</span> <span class="va">WAGP</span><span class="op">)</span></code></pre></div>
</div>
<div id="fitting-and-evaluating-the-model" class="section level3" number="10.4.2">
<h3>
<span class="header-section-number">10.4.2</span> Fitting and evaluating the model<a class="anchor" aria-label="anchor" href="#fitting-and-evaluating-the-model"><i class="fas fa-link"></i></a>
</h3>
<p>The family of modeling functions in the <strong>survey</strong> package should be used for modeling data in survey design objects, as they will take into account the replicate weights, survey design, and subpopulation structure. In the example below, we use the <code><a href="https://rdrr.io/pkg/survey/man/svyglm.html">svyglm()</a></code> function for this purpose. The formula is written using standard R formula notation, the survey design object is passed to the <code>design</code> parameter, and <code>family = quasibinomial()</code> is used to fit a logistic regression model.</p>
<div class="sourceCode" id="cb363"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://r-survey.r-forge.r-project.org/survey/">survey</a></span><span class="op">)</span>

<span class="va">migration_model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/survey/man/svyglm.html">svyglm</a></span><span class="op">(</span>
  formula <span class="op">=</span> <span class="va">migrated</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">wages</span><span class="op">)</span> <span class="op">+</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">age</span> <span class="op">+</span> <span class="va">emp_type</span> <span class="op">+</span> 
    <span class="va">child</span> <span class="op">+</span> <span class="va">married</span> <span class="op">+</span> <span class="va">college</span> <span class="op">+</span> <span class="va">PUMA</span>,
  design <span class="op">=</span> <span class="va">ri_model_svy</span>,
  family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">quasibinomial</a></span><span class="op">(</span><span class="op">)</span>
<span class="op">)</span> </code></pre></div>
<p>Once fit, we can examine the results:</p>
<div class="sourceCode" id="cb364"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">migration_model</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## svyglm(formula = migrated ~ log(wages) + sex + age + emp_type + 
##     child + married + college + PUMA, design = ri_model_svy, 
##     family = quasibinomial())
## 
## Survey design:
## Called via srvyr
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     1.359008   0.422778   3.214 0.002036 ** 
## log(wages)     -0.084403   0.041105  -2.053 0.044066 *  
## sexmale         0.213784   0.045971   4.650 1.67e-05 ***
## age            -0.066995   0.006814  -9.832 1.74e-14 ***
## emp_typepublic -0.164864   0.101945  -1.617 0.110683    
## emp_typeself   -0.280710   0.174457  -1.609 0.112453    
## childyes       -0.071226   0.106742  -0.667 0.506960    
## marriedyes     -0.251970   0.099971  -2.520 0.014185 *  
## collegeyes      0.255534   0.073107   3.495 0.000858 ***
## PUMA00102       0.025984   0.154107   0.169 0.866627    
## PUMA00103       0.205204   0.136145   1.507 0.136594    
## PUMA00104       0.148371   0.162379   0.914 0.364233    
## PUMA00201       0.121383   0.135285   0.897 0.372902    
## PUMA00300       0.390764   0.149024   2.622 0.010872 *  
## PUMA00400      -0.211051   0.177898  -1.186 0.239799    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for quasibinomial family taken to be 10979.98)
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>The model identifies some notable differences in recent migrants relative to non-migrants, controlling for other demographic factors. Males are more likely to have moved than females, as are younger people relative to older people in the subpopulation. Married individuals are more stationary, whereas college-educated individuals in the sample are much more likely to have moved. The PUMAs are included as a categorical predictor largely to control for geographic differences in the state; however the model suggests that current residents in the Newport PUMA are slightly more likely to have moved than residents of northwest Rhode Island, the reference PUMA.</p>
</div>
</div>
<div id="exercises-8" class="section level2" number="10.5">
<h2>
<span class="header-section-number">10.5</span> Exercises<a class="anchor" aria-label="anchor" href="#exercises-8"><i class="fas fa-link"></i></a>
</h2>
<ul>
<li><p>Using the dataset you acquired from the exercises in Chapter <a href="introduction-to-census-microdata.html#introduction-to-census-microdata">9</a> (or the example Wyoming dataset in that chapter), tabulate a group-wise summary using the PWGTP column and dplyr functions as you’ve learned in this section.</p></li>
<li><p>Advanced follow-up: using <code><a href="https://walker-data.com/tidycensus/reference/get_acs.html">get_acs()</a></code>, attempt to acquire the same aggregated data from the ACS. Compare your tabulated estimate with the ACS estimate.</p></li>
<li><p>Second advanced follow-up: request the same data as before, but this time with replicate weights. Calculate the margin of error as you’ve learned in this section - and if you have time, compare with the posted ACS margin of error!</p></li>
</ul>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="introduction-to-census-microdata.html"><span class="header-section-number">9</span> Introduction to Census microdata</a></div>
<div class="next"><a href="other-census-and-government-data-resources.html"><span class="header-section-number">11</span> Other Census and government data resources</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#analyzing-census-microdata"><span class="header-section-number">10</span> Analyzing Census microdata</a></li>
<li>
<a class="nav-link" href="#pums-data-and-the-tidyverse"><span class="header-section-number">10.1</span> PUMS data and the tidyverse</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#basic-tabulation-of-weights-with-tidyverse-tools"><span class="header-section-number">10.1.1</span> Basic tabulation of weights with tidyverse tools</a></li>
<li><a class="nav-link" href="#group-wise-data-tabulation"><span class="header-section-number">10.1.2</span> Group-wise data tabulation</a></li>
</ul>
</li>
<li><a class="nav-link" href="#mapping-pums-data"><span class="header-section-number">10.2</span> Mapping PUMS data</a></li>
<li>
<a class="nav-link" href="#survey-design-and-the-acs-pums"><span class="header-section-number">10.3</span> Survey design and the ACS PUMS</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#getting-replicate-weights"><span class="header-section-number">10.3.1</span> Getting replicate weights</a></li>
<li><a class="nav-link" href="#creating-a-survey-object"><span class="header-section-number">10.3.2</span> Creating a survey object</a></li>
<li><a class="nav-link" href="#calculating-estimates-and-errors-with-srvyr"><span class="header-section-number">10.3.3</span> Calculating estimates and errors with srvyr</a></li>
<li><a class="nav-link" href="#converting-standard-errors-to-margins-of-error"><span class="header-section-number">10.3.4</span> Converting standard errors to margins of error</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#modeling-with-pums-data"><span class="header-section-number">10.4</span> Modeling with PUMS data</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#data-preparation"><span class="header-section-number">10.4.1</span> Data preparation</a></li>
<li><a class="nav-link" href="#fitting-and-evaluating-the-model"><span class="header-section-number">10.4.2</span> Fitting and evaluating the model</a></li>
</ul>
</li>
<li><a class="nav-link" href="#exercises-8"><span class="header-section-number">10.5</span> Exercises</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Analyzing US Census Data</strong>: Methods, Maps, and Models in R" was written by Kyle E. Walker. It was last built on 2021-09-27.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
