<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 9 Introduction to Census microdata | Analyzing US Census Data</title>
<meta name="author" content="Kyle E. Walker">
<meta name="description" content="The previous two sections of this book cover aggregate-level analysis of US Census Bureau data. However, such analyses are limited to the pre-tabulated estimates provided by the Census Bureau....">
<meta name="generator" content="bookdown 0.22.17 with bs4_book()">
<meta property="og:title" content="Chapter 9 Introduction to Census microdata | Analyzing US Census Data">
<meta property="og:type" content="book">
<meta property="og:description" content="The previous two sections of this book cover aggregate-level analysis of US Census Bureau data. However, such analyses are limited to the pre-tabulated estimates provided by the Census Bureau....">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 9 Introduction to Census microdata | Analyzing US Census Data">
<meta name="twitter:description" content="The previous two sections of this book cover aggregate-level analysis of US Census Bureau data. However, such analyses are limited to the pre-tabulated estimates provided by the Census Bureau....">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.10.5/header-attrs.js"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.2.5.1/tabs.js"></script><script src="libs/bs3compat-0.2.5.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="libs/htmlwidgets-1.5.3/htmlwidgets.js"></script><script src="libs/plotly-binding-4.9.3/plotly.js"></script><script src="libs/typedarray-0.1/typedarray.min.js"></script><link href="libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet">
<script src="libs/crosstalk-1.1.1/js/crosstalk.min.js"></script><link href="libs/plotly-htmlwidgets-css-1.57.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="libs/plotly-main-1.57.1/plotly-latest.min.js"></script><script src="libs/d3-bundle-5.16.0/d3-bundle.min.js"></script><script src="libs/d3-lasso-0.0.5/d3-lasso.min.js"></script><script src="libs/save-svg-as-png-1.4.17/save-svg-as-png.min.js"></script><link href="libs/ggiraphjs-0.4.1/ggiraphjs.min.css" rel="stylesheet">
<script src="libs/ggiraphjs-0.4.1/ggiraphjs.min.js"></script><script src="libs/girafe-binding-0.7.10/girafe.js"></script><!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=G-6KFYZ3W36Z"></script><script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-6KFYZ3W36Z');
    </script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS -->
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="Methods, Maps, and Models in R">Analyzing US Census Data</a>:
        <small class="text-muted">Methods, Maps, and Models in R</small>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Preface</a></li>
<li><a class="" href="the-united-states-census-and-the-r-programming-language.html"><span class="header-section-number">1</span> The United States Census and the R programming language</a></li>
<li><a class="" href="an-introduction-to-tidycensus.html"><span class="header-section-number">2</span> An introduction to tidycensus</a></li>
<li><a class="" href="wrangling-census-data-with-tidyverse-tools.html"><span class="header-section-number">3</span> Wrangling Census data with tidyverse tools</a></li>
<li><a class="" href="exploring-us-census-data-with-visualization.html"><span class="header-section-number">4</span> Exploring US Census data with visualization</a></li>
<li><a class="" href="census-geographic-data-and-applications-in-r.html"><span class="header-section-number">5</span> Census geographic data and applications in R</a></li>
<li><a class="" href="mapping-census-data-with-r.html"><span class="header-section-number">6</span> Mapping Census data with R</a></li>
<li><a class="" href="spatial-analysis-with-us-census-data.html"><span class="header-section-number">7</span> Spatial analysis with US Census data</a></li>
<li><a class="" href="modeling-us-census-data.html"><span class="header-section-number">8</span> Modeling US Census data</a></li>
<li><a class="active" href="introduction-to-census-microdata.html"><span class="header-section-number">9</span> Introduction to Census microdata</a></li>
<li><a class="" href="analyzing-census-microdata.html"><span class="header-section-number">10</span> Analyzing Census microdata</a></li>
<li><a class="" href="other-census-and-government-data-resources.html"><span class="header-section-number">11</span> Other Census and government data resources</a></li>
<li><a class="" href="working-with-census-data-outside-the-united-states.html"><span class="header-section-number">12</span> Working with Census data outside the United States</a></li>
<li><a class="" href="conclusion.html">Conclusion</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="introduction-to-census-microdata" class="section level1" number="9">
<h1>
<span class="header-section-number">9</span> Introduction to Census microdata<a class="anchor" aria-label="anchor" href="#introduction-to-census-microdata"><i class="fas fa-link"></i></a>
</h1>
<p>The previous two sections of this book cover aggregate-level analysis of US Census Bureau data. However, such analyses are limited to the pre-tabulated estimates provided by the Census Bureau. While these estimates are voluminous, they may not include the level of detail required by researchers, and they are limited to analyses appropriate for aggregate-level data. In turn, many researchers turn to Census <em>microdata</em>, which are anonymized individual-level Census records, to help answer demographic questions. In 2020, tidycensus added support for American Community Survey microdata along with a series of tools to assist with analysis of these datasets. The next two chapters provide an overview of this functionality in tidycensus and help users get started analyzing and modeling ACS microdata appropriately.</p>
<div id="what-is-microdata" class="section level2" number="9.1">
<h2>
<span class="header-section-number">9.1</span> What is “microdata?”<a class="anchor" aria-label="anchor" href="#what-is-microdata"><i class="fas fa-link"></i></a>
</h2>
<p><strong>Microdata</strong> refer to individual-level data made available to researchers. In many cases, microdata reflect responses to surveys that are de-identified and anonymized, then prepared in datasets that include rich detail about survey responses. US Census microdata are available for both the decennial Census and the American Community Survey; these datasets, named <a href="https://www.census.gov/programs-surveys/acs/microdata.html">the Public Use Microdata Series (PUMS)</a>, allow for detailed cross-tabulations not available in aggregated data.</p>
<p>The ACS PUMS is available, like the aggregate data, in both 1-year and 5-year versions. The 1-year PUMS covers about 1 percent of the US population, whereas the 5-year PUMS covers about 5 percent; this means that microdata represent a smaller subset of the US population than the regular ACS. Public use microdata downloads available <a href="https://www2.census.gov/programs-surveys/acs/data/pums/2019/5-Year/">in bulk from the Census FTP server</a> or <a href="https://data.census.gov/mdat/#/search?ds=ACSPUMS5Y2019">from data.census.gov’s MDAT tool</a>.</p>
<p>The Census Bureau also operates a network of <a href="https://www.census.gov/about/adrm/fsrdc.html">Federal Statistical Research Data Centers</a> (FSRDCs) around the country that grant access to microdata with larger sample sizes and greater demographic detail. To work at one of these centers, researchers must get special government clearance and have an approved proposal with the US Census Bureau. This and the following chapter focus on the public use microdata product, which is much more accessible to researchers and analysts.</p>
<div id="microdata-resources-ipums" class="section level3" number="9.1.1">
<h3>
<span class="header-section-number">9.1.1</span> Microdata resources: IPUMS<a class="anchor" aria-label="anchor" href="#microdata-resources-ipums"><i class="fas fa-link"></i></a>
</h3>
<p>One of the most popular and comprehensive repositories for research microdata is the University of Minnesota’s IPUMS project <span class="citation">(<a href="references.html#ref-ruggles2020" role="doc-biblioref">Ruggles et al. 2020</a>)</span>. IPUMS includes Decennial US Census and ACS microdata (IPUMS USA), microdata from the Current Population Survey (IPUMS CPS), and over 100 countries around the world (IPUMS International).</p>
<div class="figure">
<span style="display:block;" id="fig:ipums-home"></span>
<img src="img/screenshots/ipums-home.png" alt="IPUMS home page" width="100%"><p class="caption">
Figure 9.1: IPUMS home page
</p>
</div>
<p>IPUMS releases microdata that are <em>harmonized,</em> which means that changing variable definitions over time are aligned by the IPUMS team to allow for coherent longitudinal analysis. Using IPUMS requires signing up for an account and making a request through their web interface, then downloading a data extract; <a href="https://developer.ipums.org/docs/apiprogram/">an API is under development</a>. IPUMS data products will be covered in more detail in Chapter <a href="other-census-and-government-data-resources.html#other-census-and-government-data-resources">11</a>, which will also introduce the <strong>ipumsr</strong> R package <span class="citation">(<a href="references.html#ref-ellis_and_burk2020" role="doc-biblioref">Ellis and Burk 2020</a>)</span> for working with IPUMS data in R.</p>
</div>
<div id="microdata-and-the-census-api" class="section level3" number="9.1.2">
<h3>
<span class="header-section-number">9.1.2</span> Microdata and the Census API<a class="anchor" aria-label="anchor" href="#microdata-and-the-census-api"><i class="fas fa-link"></i></a>
</h3>
<p>The migration of US Census data from American FactFinder to the data.census.gov tool integrated the Census Bureau’s data download interface with its API. The Census Bureau’s MDAT tool allows for flat file downloads of microdata along with API queries for microdata, marking the first time that microdata are available via the API.</p>
<div class="figure">
<span style="display:block;" id="fig:mdat-tool"></span>
<img src="img/screenshots/mdat-tool.png" alt="MDAT tool from data.census.gov" width="100%"><p class="caption">
Figure 9.2: MDAT tool from data.census.gov
</p>
</div>
<p>This means that microdata can be accessed with <code><a href="https://httr.r-lib.org/reference/GET.html">httr::GET()</a></code> requests in R, but also made ACS microdata accessible to <strong>tidycensus</strong>. In 2020, tidycensus released a range of features to support ACS microdata for R users; this functionality is covered in the remainder of this chapter.</p>
</div>
</div>
<div id="using-microdata-in-tidycensus" class="section level2" number="9.2">
<h2>
<span class="header-section-number">9.2</span> Using microdata in tidycensus<a class="anchor" aria-label="anchor" href="#using-microdata-in-tidycensus"><i class="fas fa-link"></i></a>
</h2>
<p>American Community Survey microdata are available in <strong>tidycensus</strong> by using the <code><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums()</a></code> function, which communicates with the Census API much like other tidycensus functions and returns PUMS data. Given the unique properties of Census microdata and the different structure of individual-level records as opposed to aggregate data, the data returned by <code><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums()</a></code> differs from other tidycensus functions. This section covers the basics of requesting microdata extracts with <strong>tidycensus</strong>.</p>
<div id="basic-usage-of-get_pums" class="section level3" number="9.2.1">
<h3>
<span class="header-section-number">9.2.1</span> Basic usage of <code>get_pums()</code><a class="anchor" aria-label="anchor" href="#basic-usage-of-get_pums"><i class="fas fa-link"></i></a>
</h3>
<p><code><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums()</a></code> requires specifying one or more variables and the state for which you’d like to request data. For national-level analyses, <code>state = 'all'</code> <em>can</em> get data for the entire USA by iterating over all US states, but the data can take some time to download depending on the user’s internet connection. The <code><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums()</a></code> function defaults to the 5-year ACS with <code>survey = "acs5"</code>; 1-year ACS data is available with <code>survey = "acs1"</code>. At the time of this writing, the default year is 2019; data are available back to 2006 for the 1-year ACS and 2005-2009 for the 5-year ACS.</p>
<p>Let’s take a look at a first example using <code><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums()</a></code> to request microdata for Wyoming from the 1-year 2019 ACS with information on sex, age (<code>AGEP</code>), and household type (<code>HHT</code>).</p>
<div class="sourceCode" id="cb312"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://walker-data.com/tidycensus">tidycensus</a></span><span class="op">)</span>

<span class="va">wy_pums</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums</a></span><span class="op">(</span>
  variables <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"SEX"</span>, <span class="st">"AGEP"</span>, <span class="st">"HHT"</span><span class="op">)</span>,
  state <span class="op">=</span> <span class="st">"WY"</span>,
  survey <span class="op">=</span> <span class="st">"acs1"</span>,
  year <span class="op">=</span> <span class="fl">2019</span>
<span class="op">)</span></code></pre></div>
<div class="inline-table"><table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:show-first-call">Table 9.1: </span>1-year ACS PUMS data for Wyoming
</caption>
<thead><tr>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
SERIALNO
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
SPORDER
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
WGTP
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
PWGTP
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
AGEP
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
ST
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
HHT
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
SEX
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
2019GQ0000335
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
206
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
b
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
2019GQ0000958
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
50
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
b
</td>
<td style="text-align:left;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
2019GQ0009156
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
33
</td>
<td style="text-align:right;">
75
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
b
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
2019GQ0012426
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
23
</td>
<td style="text-align:right;">
21
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
b
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
2019GQ0015243
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
209
</td>
<td style="text-align:right;">
94
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
b
</td>
<td style="text-align:left;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
2019GQ0018773
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
273
</td>
<td style="text-align:right;">
26
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
b
</td>
<td style="text-align:left;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
2019GQ0019978
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
16
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
b
</td>
<td style="text-align:left;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
2019GQ0022931
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
67
</td>
<td style="text-align:right;">
18
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
b
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
2019GQ0032421
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
113
</td>
<td style="text-align:right;">
94
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
b
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
2019GQ0033045
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
44
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
b
</td>
<td style="text-align:left;">
1
</td>
</tr>
</tbody>
</table></div>
<p>The function returns just under 6,000 rows of data with our requested variables in the columns. However, a few other variables are also returned that we did not request; these default variables are covered below.</p>
</div>
<div id="understanding-default-data-from-get_pums" class="section level3" number="9.2.2">
<h3>
<span class="header-section-number">9.2.2</span> Understanding default data from <code>get_pums()</code><a class="anchor" aria-label="anchor" href="#understanding-default-data-from-get_pums"><i class="fas fa-link"></i></a>
</h3>
<p><code><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums()</a></code> returns some technical variables by default without the user needing to request them specifically. These technical variables are essential for uniquely identifying observations in the dataset and eventually performing any analysis and modeling. These default technical variables include:</p>
<ul>
<li><p><code>SERIALNO</code>: a serial number that uniquely identifies households in the sample;</p></li>
<li><p><code>SPORDER</code>: the order of the person in the household, which when combined with <code>SERIALNO</code> uniquely identifies a person;</p></li>
<li><p><code>WGTP</code>: the household weight;</p></li>
<li><p><code>PWGTP</code>: the person weight;</p></li>
<li><p><code>ST</code>: the state FIPS code.</p></li>
</ul>
<p>Given that PUMS data are a <em>sample</em> of the US population, the weights columns must be used for analysis. In general terms, we can interpret the weights as “the number of observations in the general population represented by this particular row in the dataset.” In turn, a row with a <code>PWGTP</code> value of 50 represents about 50 people in Wyoming with the same demographic characteristics of the “person” in that row.</p>
<p>Inferences about population characteristics can be made by summing over the weights columns. For example, let’s say we want to get an estimate of the number of people in Wyoming who are 50 years old in 2019, and compare this with the total population in Wyoming. We can filter the dataset for rows that match the condition <code>AGEP == 50</code>, then sum over the <code>PWGTP</code> column.</p>
<div class="sourceCode" id="cb313"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span>

<span class="va">wy_age_50</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">wy_pums</span>, <span class="va">AGEP</span> <span class="op">==</span> <span class="fl">50</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">wy_pums</span><span class="op">$</span><span class="va">PWGTP</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 578759</code></pre>
<div class="sourceCode" id="cb315"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">wy_age_50</span><span class="op">$</span><span class="va">PWGTP</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 4756</code></pre>
<p>Our data suggest that of the 578,759 people in Wyoming in 2019, about 4,756 were 50 years old. Of course, this estimate will be subject to a margin of error; the topic of error calculations from PUMS data will be covered in the next chapter.</p>
<p>It is important to note that <code><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums()</a></code> returns two separate weights columns: one for households and one for persons. Let’s take a look at a single household in the Wyoming dataset to examine this further.</p>
<div class="sourceCode" id="cb317"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">wy_hh_example</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">wy_pums</span>, <span class="va">SERIALNO</span> <span class="op">==</span> <span class="st">"2019HU0456721"</span><span class="op">)</span>

<span class="va">wy_hh_example</span></code></pre></div>
<pre><code>## # A tibble: 4 × 8
##   SERIALNO      SPORDER  WGTP PWGTP  AGEP ST    HHT   SEX  
##   &lt;chr&gt;           &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;
## 1 2019HU0456721       1   146   146    40 56    1     2    
## 2 2019HU0456721       2   146   132    45 56    1     1    
## 3 2019HU0456721       3   146    94     8 56    1     2    
## 4 2019HU0456721       4   146   154     5 56    1     1</code></pre>
<p>This household includes a woman aged 40, a man aged 45, and two children: a girl aged 8 and a boy aged 5. The <code>HHT</code> value is 1, which tells us that this is a married-couple household. Notably, the household weight value, <code>WGTP</code>, is identical for all household members, whereas the person weight value, <code>PWGTP</code>, is not.</p>
<p>Microdata retrieved from the Census API are a hybrid of both household-level data and person-level data, which means that analysts need to take care to use appropriate weights and filters for household-level or person-level analyses. For example, to determine the number of households in Wyoming, the dataset should be filtered to records where the <code>SPORDER</code> column is equal to 1 then summed over the <code>WGTP</code> column. Persons living in group quarters will be excluded automatically as they have a household weight of 0.</p>
<div class="sourceCode" id="cb319"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">wy_households</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">wy_pums</span>, <span class="va">SPORDER</span> <span class="op">==</span> <span class="fl">1</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">wy_households</span><span class="op">$</span><span class="va">WGTP</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 233126</code></pre>
</div>
</div>
<div id="working-with-pums-variables" class="section level2" number="9.3">
<h2>
<span class="header-section-number">9.3</span> Working with PUMS variables<a class="anchor" aria-label="anchor" href="#working-with-pums-variables"><i class="fas fa-link"></i></a>
</h2>
<p>While the ACS PUMS dataset does not include tens of thousands of variables choices like its aggregate counterpart, it nonetheless includes variables and variable codes that can be difficult to understand without a data dictionary. In the Wyoming example above, only interpretation of the <code>AGEP</code> column for age is straightforward. <code>HHT</code>, for household type, and <code>SEX</code>, for sex, are coded as integers represented as character strings. To help users understand the meanings of these codes, tidycensus includes a built-in dataset, <code>pums_variables</code>, that can be viewed, filtered, and browsed.</p>
<div id="variables-available-in-the-acs-pums" class="section level3" number="9.3.1">
<h3>
<span class="header-section-number">9.3.1</span> Variables available in the ACS PUMS<a class="anchor" aria-label="anchor" href="#variables-available-in-the-acs-pums"><i class="fas fa-link"></i></a>
</h3>
<p>As with the data dictionaries for the decennial Census and aggregate ACS obtained with <code><a href="https://walker-data.com/tidycensus/reference/load_variables.html">load_variables()</a></code>, it is advisable to browse the PUMS data dictionary, <code>pums_variables</code>, with the <code><a href="https://rdrr.io/r/utils/View.html">View()</a></code> function in RStudio.</p>
<div class="sourceCode" id="cb321"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/View.html">View</a></span><span class="op">(</span><span class="va">pums_variables</span><span class="op">)</span></code></pre></div>
<p><code>pums_variables</code> is a long-form dataset that organizes specific <em>value codes</em> by variable so you know what you can get with <code><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums()</a></code>. You’ll use information in the <code>var_code</code> column to fetch variables, but pay close attention to the <code>var_label</code>, <code>val_min</code>, <code>val_max</code>, <code>val_label</code>, and <code>data_type</code> columns. These columns should be interpreted as follows:</p>
<ul>
<li>
<code>var_code</code> gives you the variable codes that should be supplied to the <code>variables</code> parameter (as a character vector) in <code><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums()</a></code>. These variables will be represented in the columns of your output dataset.</li>
<li>
<code>var_label</code> is a more informative description of the variable’s topic.</li>
<li>
<code>data_type</code> is one of <code>"chr"</code>, for categorical variables that will be returned as R character strings, or <code>"num"</code>, for variables that will be returned as numeric.</li>
<li>
<code>val_min</code> and <code>val_max</code> provide information about the meaning of the data values. For categorical variables, these two columns will be the same; for numeric variables, they will give you the possible range of data values.</li>
<li>
<code>val_label</code> contains the value labels, which are particularly important for understanding the content of categorical variables.</li>
</ul>
</div>
<div id="recoding-pums-variables" class="section level3" number="9.3.2">
<h3>
<span class="header-section-number">9.3.2</span> Recoding PUMS variables<a class="anchor" aria-label="anchor" href="#recoding-pums-variables"><i class="fas fa-link"></i></a>
</h3>
<p>A typical <strong>tidycensus</strong> workflow covered earlier in this book involves browsing the appropriate data dictionary, choosing variable IDs, and using those IDs in your scripts and workflows. Analysts will likely follow this same process with <code><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums()</a></code>, but can also use the argument <code>recode = TRUE</code> to return additional contextual information with the requested data. <code>recode = TRUE</code> instructs <code><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums()</a></code> to append recoded columns to your returned dataset based on information available in <code>pums_variables</code>. Let’s take a look at the Wyoming example with <code>recode = TRUE</code>.</p>
<div class="sourceCode" id="cb322"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">wy_pums_recoded</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums</a></span><span class="op">(</span>
  variables <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"SEX"</span>, <span class="st">"AGEP"</span>, <span class="st">"HHT"</span><span class="op">)</span>,
  state <span class="op">=</span> <span class="st">"WY"</span>,
  survey <span class="op">=</span> <span class="st">"acs1"</span>,
  year <span class="op">=</span> <span class="fl">2019</span>,
  recode <span class="op">=</span> <span class="cn">TRUE</span>
<span class="op">)</span></code></pre></div>
<div class="inline-table"><table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:show-recode">Table 9.2: </span>Recoded PUMS data for Wyoming
</caption>
<thead><tr>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
SERIALNO
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
SPORDER
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
WGTP
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
PWGTP
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
AGEP
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
ST
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
HHT
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
SEX
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
ST_label
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
HHT_label
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
SEX_label
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
2019GQ0000335
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
206
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
b
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
Wyoming/WY
</td>
<td style="text-align:left;">
N/A (GQ/vacant)
</td>
<td style="text-align:left;">
Female
</td>
</tr>
<tr>
<td style="text-align:left;">
2019GQ0000958
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
50
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
b
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
Wyoming/WY
</td>
<td style="text-align:left;">
N/A (GQ/vacant)
</td>
<td style="text-align:left;">
Male
</td>
</tr>
<tr>
<td style="text-align:left;">
2019GQ0009156
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
33
</td>
<td style="text-align:right;">
75
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
b
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
Wyoming/WY
</td>
<td style="text-align:left;">
N/A (GQ/vacant)
</td>
<td style="text-align:left;">
Female
</td>
</tr>
<tr>
<td style="text-align:left;">
2019GQ0012426
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
23
</td>
<td style="text-align:right;">
21
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
b
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
Wyoming/WY
</td>
<td style="text-align:left;">
N/A (GQ/vacant)
</td>
<td style="text-align:left;">
Female
</td>
</tr>
<tr>
<td style="text-align:left;">
2019GQ0015243
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
209
</td>
<td style="text-align:right;">
94
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
b
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
Wyoming/WY
</td>
<td style="text-align:left;">
N/A (GQ/vacant)
</td>
<td style="text-align:left;">
Male
</td>
</tr>
<tr>
<td style="text-align:left;">
2019GQ0018773
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
273
</td>
<td style="text-align:right;">
26
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
b
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
Wyoming/WY
</td>
<td style="text-align:left;">
N/A (GQ/vacant)
</td>
<td style="text-align:left;">
Male
</td>
</tr>
<tr>
<td style="text-align:left;">
2019GQ0019978
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
16
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
b
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
Wyoming/WY
</td>
<td style="text-align:left;">
N/A (GQ/vacant)
</td>
<td style="text-align:left;">
Male
</td>
</tr>
<tr>
<td style="text-align:left;">
2019GQ0022931
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
67
</td>
<td style="text-align:right;">
18
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
b
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
Wyoming/WY
</td>
<td style="text-align:left;">
N/A (GQ/vacant)
</td>
<td style="text-align:left;">
Female
</td>
</tr>
<tr>
<td style="text-align:left;">
2019GQ0032421
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
113
</td>
<td style="text-align:right;">
94
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
b
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
Wyoming/WY
</td>
<td style="text-align:left;">
N/A (GQ/vacant)
</td>
<td style="text-align:left;">
Female
</td>
</tr>
<tr>
<td style="text-align:left;">
2019GQ0033045
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
44
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
b
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
Wyoming/WY
</td>
<td style="text-align:left;">
N/A (GQ/vacant)
</td>
<td style="text-align:left;">
Male
</td>
</tr>
</tbody>
</table></div>
<p>Note that the dataset returns three new columns: <code>ST_label</code>, <code>HHT_label</code>, and <code>SEX_label</code> which include longer and more informative descriptions of the value labels. These columns are returned as ordered factors that preserve the original ordering of the columns independent of their alphabetical order. Numeric columns like <code>AGEP</code> are not recoded as the data values reflect numbers, not a categorical label.</p>
</div>
<div id="using-variables-filters" class="section level3" number="9.3.3">
<h3>
<span class="header-section-number">9.3.3</span> Using variables filters<a class="anchor" aria-label="anchor" href="#using-variables-filters"><i class="fas fa-link"></i></a>
</h3>
<p>PUMS datasets, especially those from the 5-year ACS, can get quite large. Even users with speedy internet connections will need to be patient when downloading what could be millions of records from the Census API and potentially risk internet hiccups. When only subsets of data are required for an analysis, the <code>variables_filter</code> argument can return a subset of data from the API, reducing long download times.</p>
<p>The <code>variables_filter</code> argument should be supplied as a named list where variable names (which can be quoted or unquoted) are paired with a data value or vector of data values to be requested from the API. The “filter” works by passing a special query to the Census API which will only return a subset of data, meaning that the entire dataset does not need to be first downloaded then filtered on the R side. This leads to substantial time savings for targeted queries.</p>
<p>In the example below, the Wyoming request is modified with <code>variables_filter</code> to return only women (<code>SEX = 2</code>) between the ages of 30 and 49, but this time from the 5-year ACS PUMS.</p>
<div class="sourceCode" id="cb323"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">wy_pums_filtered</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums</a></span><span class="op">(</span>
  variables <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"SEX"</span>, <span class="st">"AGEP"</span>, <span class="st">"HHT"</span><span class="op">)</span>,
  state <span class="op">=</span> <span class="st">"WY"</span>,
  survey <span class="op">=</span> <span class="st">"acs5"</span>,
  variables_filter <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>
    SEX <span class="op">=</span> <span class="fl">2</span>,
    AGEP <span class="op">=</span> <span class="fl">30</span><span class="op">:</span><span class="fl">49</span>
  <span class="op">)</span>,
  year <span class="op">=</span> <span class="fl">2019</span>
<span class="op">)</span></code></pre></div>
<div class="inline-table"><table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:show-filter">Table 9.3: </span>Filtered extract of Wyoming PUMS data
</caption>
<thead><tr>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
SERIALNO
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
SPORDER
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
WGTP
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
PWGTP
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
AGEP
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
ST
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
HHT
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
SEX
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
2015000004982
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
28
</td>
<td style="text-align:right;">
29
</td>
<td style="text-align:right;">
39
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000014993
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
18
</td>
<td style="text-align:right;">
19
</td>
<td style="text-align:right;">
44
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000016130
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
22
</td>
<td style="text-align:right;">
23
</td>
<td style="text-align:right;">
48
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000025094
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
31
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000032486
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
65
</td>
<td style="text-align:right;">
65
</td>
<td style="text-align:right;">
36
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000044674
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
40
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000045979
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
18
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
49
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000052006
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000053688
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
21
</td>
<td style="text-align:right;">
22
</td>
<td style="text-align:right;">
40
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000067452
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
43
</td>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
2
</td>
</tr>
</tbody>
</table></div>
<p>The returned dataset reflects the filter request, with data values in the <code>AGEP</code> column only ranging between 30 and 49 and the <code>SEX</code> column only including 2, for female.</p>
</div>
</div>
<div id="public-use-microdata-areas-pumas" class="section level2" number="9.4">
<h2>
<span class="header-section-number">9.4</span> Public Use Microdata Areas (PUMAs)<a class="anchor" aria-label="anchor" href="#public-use-microdata-areas-pumas"><i class="fas fa-link"></i></a>
</h2>
<p>One of the steps the Census Bureau takes to preserve anonymity in the PUMS datasets is limiting the geographical detail in the data. Granular Census geographical information like the Census tract or block group of residence for individuals in the PUMS samples are not available. That said, some geographical information is available in the PUMS samples in the form of the Public Use Microdata Area, or PUMA.</p>
<div id="what-is-a-puma" class="section level3" number="9.4.1">
<h3>
<span class="header-section-number">9.4.1</span> What is a PUMA?<a class="anchor" aria-label="anchor" href="#what-is-a-puma"><i class="fas fa-link"></i></a>
</h3>
<p>Public Use Microdata Areas (PUMAs) are the smallest available geographies at which records are identifiable in the PUMS datasets. PUMAs are redrawn with each decennial US Census, and typically are home to between 100,000 - 200,000 people when drawn, although some may be much larger by the end of a Census cycle. In large cities, a PUMA will represent a collection of nearby neighborhoods; in rural areas, it might represent several counties across a large area of a state.</p>
<div class="rmdtip">
<p>At the time of this writing, PUMA geographies correspond to the 2010 Census definitions, even. While PUMAs are redrawn with each decennial US Census, their release lags the decennial Census by a couple of years. To determine appropriate PUMA geographies, the Census Bureau consults with State Data Centers (SDCs) and incorporates their suggested revisions to these geographies. For 2020 PUMAs, this process takes place through the 2021 calendar year. This means that the updated PUMA geographies, and their incorporation into PUMS datasets, are planned for public release in the summer of 2022. For more information, visit <a href="https://www.census.gov/programs-surveys/geography/guidance/geo-areas/pumas/2020pumas.html" class="uri">https://www.census.gov/programs-surveys/geography/guidance/geo-areas/pumas/2020pumas.html</a>.</p>
</div>
<p>PUMA geographies can be obtained and reviewed with the <code><a href="https://rdrr.io/pkg/tigris/man/pumas.html">pumas()</a></code> function in the <strong>tigris</strong> package. Let’s take a look at PUMA geographies for the state of Wyoming:</p>
<div class="sourceCode" id="cb324"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/walkerke/tigris">tigris</a></span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/options.html">options</a></span><span class="op">(</span>tigris_use_cache <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>

<span class="va">wy_pumas</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/tigris/man/pumas.html">pumas</a></span><span class="op">(</span>state <span class="op">=</span> <span class="st">"WY"</span>, cb <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>

<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">wy_pumas</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_void</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="figure">
<span style="display:block;" id="fig:plot-pumas"></span>
<img src="09-introduction-to-microdata_files/figure-html/plot-pumas-1.png" alt="Basic map of PUMAs in Wyoming" width="100%"><p class="caption">
Figure 9.3: Basic map of PUMAs in Wyoming
</p>
</div>
<p>There are five PUMAs in Wyoming, largely covering large rural areas of the state, although the smallest PUMA by area covers the more urban southeast corner of the state. The returned object includes a <code>NAME10</code> column with an informative description of the PUMAs:</p>
<div class="sourceCode" id="cb325"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">wy_pumas</span><span class="op">$</span><span class="va">NAME10</span></code></pre></div>
<pre><code>## [1] "Sheridan, Park, Teton, Lincoln &amp; Big Horn Counties"                                 
## [2] "Sweetwater, Fremont, Uinta, Sublette &amp; Hot Springs Counties--Wind River Reservation"
## [3] "Campbell, Goshen, Platte, Johnson, Washakie, Weston, Crook &amp; Niobrara Counties"     
## [4] "Natrona, Carbon &amp; Converse Counties"                                                
## [5] "Laramie &amp; Albany Counties"</code></pre>
<p>In a denser urban area, PUMAs will reflect subsections of major cities and are drawn in attempts to reflect meaningful local areas. In New York City, for example, PUMAs are drawn to align with recognized community districts in the city.</p>
<div class="sourceCode" id="cb327"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">nyc_pumas</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/tigris/man/pumas.html">pumas</a></span><span class="op">(</span>state <span class="op">=</span> <span class="st">"NY"</span>, cb <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="fu">str_detect</span><span class="op">(</span><span class="va">NAME10</span>, <span class="st">"NYC"</span><span class="op">)</span><span class="op">)</span>

<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">nyc_pumas</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_void</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="figure">
<span style="display:block;" id="fig:nyc-pumas"></span>
<img src="09-introduction-to-microdata_files/figure-html/nyc-pumas-1.png" alt="Map of PUMAs in New York City" width="100%"><p class="caption">
Figure 9.4: Map of PUMAs in New York City
</p>
</div>
<p>The names of NYC’s PUMAs themselves reflect the community districts in the geographic data returned by <strong>tigris</strong>.</p>
<div class="sourceCode" id="cb328"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">nyc_pumas</span><span class="op">$</span><span class="va">NAME10</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">5</span><span class="op">]</span></code></pre></div>
<pre><code>## [1] "NYC-Manhattan Community District 11--East Harlem"                                  
## [2] "NYC-Manhattan Community District 8--Upper East Side"                               
## [3] "NYC-Bronx Community District 11--Pelham Parkway, Morris Park &amp; Laconia"            
## [4] "NYC-Manhattan Community District 9--Hamilton Heights, Manhattanville &amp; West Harlem"
## [5] "NYC-Brooklyn Community District 12--Borough Park, Kensington &amp; Ocean Parkway"</code></pre>
</div>
<div id="working-with-pumas-in-pums-data" class="section level3" number="9.4.2">
<h3>
<span class="header-section-number">9.4.2</span> Working with PUMAs in PUMS data<a class="anchor" aria-label="anchor" href="#working-with-pumas-in-pums-data"><i class="fas fa-link"></i></a>
</h3>
<p>PUMA information is available with the variable code <code>PUMA</code> in <code><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums()</a></code>. Use <code>PUMA</code> like any other variable to return information about the PUMA of residence for the individual records.</p>
<div class="sourceCode" id="cb330"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">wy_age_by_puma</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums</a></span><span class="op">(</span>
  variables <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"PUMA"</span>, <span class="st">"AGEP"</span><span class="op">)</span>,
  state <span class="op">=</span> <span class="st">"WY"</span>,
  survey <span class="op">=</span> <span class="st">"acs5"</span>
<span class="op">)</span></code></pre></div>
<div class="inline-table"><table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:show-pumas">Table 9.4: </span>Wyoming microdata with PUMA and age information
</caption>
<thead><tr>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
SERIALNO
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
SPORDER
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
WGTP
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
PWGTP
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
AGEP
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
PUMA
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
ST
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
2015000001990
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
27
</td>
<td style="text-align:right;">
26
</td>
<td style="text-align:right;">
67
</td>
<td style="text-align:left;">
00300
</td>
<td style="text-align:left;">
56
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000006752
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
86
</td>
<td style="text-align:left;">
00100
</td>
<td style="text-align:left;">
56
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000006752
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
83
</td>
<td style="text-align:left;">
00100
</td>
<td style="text-align:left;">
56
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000006847
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
29
</td>
<td style="text-align:right;">
29
</td>
<td style="text-align:right;">
61
</td>
<td style="text-align:left;">
00300
</td>
<td style="text-align:left;">
56
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000007045
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
23
</td>
<td style="text-align:right;">
23
</td>
<td style="text-align:right;">
62
</td>
<td style="text-align:left;">
00300
</td>
<td style="text-align:left;">
56
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000007045
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
23
</td>
<td style="text-align:right;">
19
</td>
<td style="text-align:right;">
66
</td>
<td style="text-align:left;">
00300
</td>
<td style="text-align:left;">
56
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000007045
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
23
</td>
<td style="text-align:right;">
34
</td>
<td style="text-align:right;">
35
</td>
<td style="text-align:left;">
00300
</td>
<td style="text-align:left;">
56
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000007382
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
33
</td>
<td style="text-align:left;">
00500
</td>
<td style="text-align:left;">
56
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000010448
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
69
</td>
<td style="text-align:left;">
00100
</td>
<td style="text-align:left;">
56
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000010448
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
77
</td>
<td style="text-align:left;">
00100
</td>
<td style="text-align:left;">
56
</td>
</tr>
</tbody>
</table></div>
<p>PUMA IDs are replicated across states, so the <code>PUMA</code> column should be combined with the <code>ST</code> column to uniquely identify PUMAs when performing multi-state analyses.</p>
<p>The <code>puma</code> argument in <code><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums()</a></code> can also be used to obtain data for a specific PUMA or multiple PUMAs. Like the <code>variables_filter</code> parameter, <code>puma</code> uses a query on the API side to reduce long download times for users only interested in a geographical subset of data.</p>
<div class="sourceCode" id="cb331"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">wy_puma_subset</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums</a></span><span class="op">(</span>
  variables <span class="op">=</span> <span class="st">"AGEP"</span>,
  state <span class="op">=</span> <span class="st">"WY"</span>,
  survey <span class="op">=</span> <span class="st">"acs5"</span>,
  puma <span class="op">=</span> <span class="st">"00500"</span>
<span class="op">)</span></code></pre></div>
<div class="inline-table"><table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:show-subset-puma">Table 9.5: </span>Microdata for PUMA 00500 in Wyoming
</caption>
<thead><tr>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
SERIALNO
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
SPORDER
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
WGTP
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
PWGTP
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
AGEP
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
PUMA
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
ST
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
2015000010667
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
38
</td>
<td style="text-align:left;">
00500
</td>
<td style="text-align:left;">
56
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000010667
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
36
</td>
<td style="text-align:left;">
00500
</td>
<td style="text-align:left;">
56
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000010667
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
00500
</td>
<td style="text-align:left;">
56
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000018572
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
80
</td>
<td style="text-align:left;">
00500
</td>
<td style="text-align:left;">
56
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000040346
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
24
</td>
<td style="text-align:right;">
23
</td>
<td style="text-align:right;">
54
</td>
<td style="text-align:left;">
00500
</td>
<td style="text-align:left;">
56
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000040346
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
24
</td>
<td style="text-align:right;">
31
</td>
<td style="text-align:right;">
55
</td>
<td style="text-align:left;">
00500
</td>
<td style="text-align:left;">
56
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000042859
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
60
</td>
<td style="text-align:left;">
00500
</td>
<td style="text-align:left;">
56
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000042859
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
53
</td>
<td style="text-align:left;">
00500
</td>
<td style="text-align:left;">
56
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000047414
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
60
</td>
<td style="text-align:left;">
00500
</td>
<td style="text-align:left;">
56
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000047414
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
35
</td>
<td style="text-align:right;">
72
</td>
<td style="text-align:left;">
00500
</td>
<td style="text-align:left;">
56
</td>
</tr>
</tbody>
</table></div>
<p>For multi-state geographical queries, the <code>puma</code> argument must be adapted slightly due to the aforementioned possibility that PUMA IDs will be replicated across states. To perform a multi-state query by PUMA, specify <code>state = "multiple"</code> and pass a named vector of state/PUMA pairs to the <code>puma</code> parameter.</p>
<div class="sourceCode" id="cb332"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">twostate_puma_subset</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums</a></span><span class="op">(</span>
  variables <span class="op">=</span> <span class="st">"AGEP"</span>,
  state <span class="op">=</span> <span class="st">"multiple"</span>,
  survey <span class="op">=</span> <span class="st">"acs5"</span>,
  puma <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"WY"</span> <span class="op">=</span> <span class="st">"00500"</span>, <span class="st">"UT"</span> <span class="op">=</span> <span class="st">"05001"</span><span class="op">)</span>
<span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb333"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">style_data</span><span class="op">(</span><span class="va">twostate_puma_subset</span>, caption <span class="op">=</span> <span class="st">"Data for PUMA 00500 in Wyoming and PUMA 05001 in Utah"</span><span class="op">)</span></code></pre></div>
<div class="inline-table"><table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:show-multistate-pumas">Table 9.6: </span>Data for PUMA 00500 in Wyoming and PUMA 05001 in Utah
</caption>
<thead><tr>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
SERIALNO
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
SPORDER
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
WGTP
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
PWGTP
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
AGEP
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
PUMA
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
ST
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
2015000003167
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
22
</td>
<td style="text-align:right;">
22
</td>
<td style="text-align:right;">
55
</td>
<td style="text-align:left;">
05001
</td>
<td style="text-align:left;">
49
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000003167
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
22
</td>
<td style="text-align:right;">
28
</td>
<td style="text-align:right;">
50
</td>
<td style="text-align:left;">
05001
</td>
<td style="text-align:left;">
49
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000003167
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
22
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:left;">
05001
</td>
<td style="text-align:left;">
49
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000003167
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
22
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:left;">
05001
</td>
<td style="text-align:left;">
49
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000003167
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
22
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:left;">
05001
</td>
<td style="text-align:left;">
49
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000006810
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
23
</td>
<td style="text-align:left;">
05001
</td>
<td style="text-align:left;">
49
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000008464
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
24
</td>
<td style="text-align:right;">
24
</td>
<td style="text-align:right;">
23
</td>
<td style="text-align:left;">
05001
</td>
<td style="text-align:left;">
49
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000008464
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
24
</td>
<td style="text-align:right;">
23
</td>
<td style="text-align:right;">
22
</td>
<td style="text-align:left;">
05001
</td>
<td style="text-align:left;">
49
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000010667
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
38
</td>
<td style="text-align:left;">
00500
</td>
<td style="text-align:left;">
56
</td>
</tr>
<tr>
<td style="text-align:left;">
2015000010667
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
36
</td>
<td style="text-align:left;">
00500
</td>
<td style="text-align:left;">
56
</td>
</tr>
</tbody>
</table></div>
<p>The returned data include neighboring areas in Wyoming and Utah.</p>
</div>
</div>
<div id="exercises-7" class="section level2" number="9.5">
<h2>
<span class="header-section-number">9.5</span> Exercises<a class="anchor" aria-label="anchor" href="#exercises-7"><i class="fas fa-link"></i></a>
</h2>
<ul>
<li><p>Try requesting PUMS data using <code><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums()</a></code> yourselves, but for a state other than Wyoming.</p></li>
<li><p>Use the <code>pums_variables</code> dataset to browse the available variables in the PUMS. Create a custom query with <code><a href="https://walker-data.com/tidycensus/reference/get_pums.html">get_pums()</a></code> to request data for variables other than those we’ve used in the above examples.</p></li>
</ul>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="modeling-us-census-data.html"><span class="header-section-number">8</span> Modeling US Census data</a></div>
<div class="next"><a href="analyzing-census-microdata.html"><span class="header-section-number">10</span> Analyzing Census microdata</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#introduction-to-census-microdata"><span class="header-section-number">9</span> Introduction to Census microdata</a></li>
<li>
<a class="nav-link" href="#what-is-microdata"><span class="header-section-number">9.1</span> What is “microdata?”</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#microdata-resources-ipums"><span class="header-section-number">9.1.1</span> Microdata resources: IPUMS</a></li>
<li><a class="nav-link" href="#microdata-and-the-census-api"><span class="header-section-number">9.1.2</span> Microdata and the Census API</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#using-microdata-in-tidycensus"><span class="header-section-number">9.2</span> Using microdata in tidycensus</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#basic-usage-of-get_pums"><span class="header-section-number">9.2.1</span> Basic usage of get_pums()</a></li>
<li><a class="nav-link" href="#understanding-default-data-from-get_pums"><span class="header-section-number">9.2.2</span> Understanding default data from get_pums()</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#working-with-pums-variables"><span class="header-section-number">9.3</span> Working with PUMS variables</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#variables-available-in-the-acs-pums"><span class="header-section-number">9.3.1</span> Variables available in the ACS PUMS</a></li>
<li><a class="nav-link" href="#recoding-pums-variables"><span class="header-section-number">9.3.2</span> Recoding PUMS variables</a></li>
<li><a class="nav-link" href="#using-variables-filters"><span class="header-section-number">9.3.3</span> Using variables filters</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#public-use-microdata-areas-pumas"><span class="header-section-number">9.4</span> Public Use Microdata Areas (PUMAs)</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#what-is-a-puma"><span class="header-section-number">9.4.1</span> What is a PUMA?</a></li>
<li><a class="nav-link" href="#working-with-pumas-in-pums-data"><span class="header-section-number">9.4.2</span> Working with PUMAs in PUMS data</a></li>
</ul>
</li>
<li><a class="nav-link" href="#exercises-7"><span class="header-section-number">9.5</span> Exercises</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Analyzing US Census Data</strong>: Methods, Maps, and Models in R" was written by Kyle E. Walker. It was last built on 2021-08-27.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
